// Generated by `bun run codegen` in apps/ios. Don't edit it.
#if canImport(UIKit)
import UIKit

enum WebShortcutAction: String {
  case formatParagraph
  case formatHeading
  case formatBulletList
  case formatNumberedList
  case formatCheckList
  case formatCode
  case formatQuote
  case lowercase
  case uppercase
  case capitalize
  case strikeThrough
  case indent
  case outdent
  case centerAlign
  case leftAlign
  case rightAlign
  case justifyAlign
  case `subscript`
  case superscript
  case insertCodeBlock
  case increaseFontSize
  case decreaseFontSize
  case clearFormatting
  case insertLink
}

struct WebKeyboardShortcut {
  let input: String
  let modifiers: UIKeyModifierFlags
  let action: WebShortcutAction
}

let webKeyboardShortcuts: [WebKeyboardShortcut] = [
  WebKeyboardShortcut(input: #"0"#, modifiers: [.command, .alternate], action: .formatParagraph),
  WebKeyboardShortcut(input: #"1"#, modifiers: [.command, .alternate], action: .formatHeading),
  WebKeyboardShortcut(input: #"2"#, modifiers: [.command, .alternate], action: .formatHeading),
  WebKeyboardShortcut(input: #"3"#, modifiers: [.command, .alternate], action: .formatHeading),
  WebKeyboardShortcut(input: #"4"#, modifiers: [.command, .alternate], action: .formatBulletList),
  WebKeyboardShortcut(input: #"5"#, modifiers: [.command, .alternate], action: .formatNumberedList),
  WebKeyboardShortcut(input: #"6"#, modifiers: [.command, .alternate], action: .formatCheckList),
  WebKeyboardShortcut(input: #"c"#, modifiers: [.command, .alternate], action: .formatCode),
  WebKeyboardShortcut(input: #"q"#, modifiers: [.command, .alternate], action: .formatQuote),
  WebKeyboardShortcut(input: #"1"#, modifiers: [.command, .shift], action: .lowercase),
  WebKeyboardShortcut(input: #"2"#, modifiers: [.command, .shift], action: .uppercase),
  WebKeyboardShortcut(input: #"3"#, modifiers: [.command, .shift], action: .capitalize),
  WebKeyboardShortcut(input: #"s"#, modifiers: [.command, .shift], action: .strikeThrough),
  WebKeyboardShortcut(input: #"]"#, modifiers: [.command], action: .indent),
  WebKeyboardShortcut(input: #"["#, modifiers: [.command], action: .outdent),
  WebKeyboardShortcut(input: #"e"#, modifiers: [.command, .shift], action: .centerAlign),
  WebKeyboardShortcut(input: #"l"#, modifiers: [.command, .shift], action: .leftAlign),
  WebKeyboardShortcut(input: #"r"#, modifiers: [.command, .shift], action: .rightAlign),
  WebKeyboardShortcut(input: #"j"#, modifiers: [.command, .shift], action: .justifyAlign),
  WebKeyboardShortcut(input: #","#, modifiers: [.command], action: .subscript),
  WebKeyboardShortcut(input: #"."#, modifiers: [.command], action: .superscript),
  WebKeyboardShortcut(input: #"c"#, modifiers: [.command, .shift], action: .insertCodeBlock),
  WebKeyboardShortcut(input: #"."#, modifiers: [.command, .shift], action: .increaseFontSize),
  WebKeyboardShortcut(input: #","#, modifiers: [.command, .shift], action: .decreaseFontSize),
  WebKeyboardShortcut(input: #"\"#, modifiers: [.command], action: .clearFormatting),
  WebKeyboardShortcut(input: #"k"#, modifiers: [.command], action: .insertLink),
]

struct WebBlockChoice {
  let type: String
  let label: String
}

let webBlockChoices: [WebBlockChoice] = [
  WebBlockChoice(type: #"paragraph"#, label: #"Normal"#),
  WebBlockChoice(type: #"h1"#, label: #"Heading 1"#),
  WebBlockChoice(type: #"h2"#, label: #"Heading 2"#),
  WebBlockChoice(type: #"h3"#, label: #"Heading 3"#),
  WebBlockChoice(type: #"h4"#, label: #"Heading 4"#),
  WebBlockChoice(type: #"bullet"#, label: #"Bulleted list"#),
  WebBlockChoice(type: #"number"#, label: #"Numbered list"#),
  WebBlockChoice(type: #"check"#, label: #"Check list"#),
  WebBlockChoice(type: #"toggle"#, label: #"Toggle"#),
  WebBlockChoice(type: #"toggle-h1"#, label: #"Toggle heading 1"#),
  WebBlockChoice(type: #"toggle-h2"#, label: #"Toggle heading 2"#),
  WebBlockChoice(type: #"toggle-h3"#, label: #"Toggle heading 3"#),
  WebBlockChoice(type: #"quote"#, label: #"Quote"#),
  WebBlockChoice(type: #"code"#, label: #"Code block"#),
]
#endif
