// Generated by `bun run codegen` in apps/ios. Don't edit it.

extension DocumentTypography {
  /// document.css and globals.css in apps/lexidraw.
  static let web = DocumentTypography(
    color: .foreground,
    lineHeight: 1.6,
    blockAfter: 0.75,
    headingWeight: 600,
    headings: [
      "h1": Heading(fontSize: 1.875, lineHeight: 1.25, letterSpacing: -0.015, before: 1.6, after: 0.4, color: .heading),
      "h2": Heading(fontSize: 1.5, lineHeight: 1.3, letterSpacing: -0.01, before: 1.6, after: 0.4, color: .heading),
      "h3": Heading(fontSize: 1.25, lineHeight: 1.4, letterSpacing: 0, before: 1.5, after: 0.35, color: .heading),
      "h4": Heading(fontSize: 1.0625, lineHeight: 1.5, letterSpacing: 0, before: 1.5, after: 0.25, color: .heading),
      "h5": Heading(fontSize: 1, lineHeight: 1.5, letterSpacing: 0, before: 1.25, after: 0.25, color: .heading),
      "h6": Heading(fontSize: 0.875, lineHeight: 1.5, letterSpacing: 0, before: 1.25, after: 0.25, color: .mutedForeground),
    ],
    adjacentHeadingBefore: 0.5,
    narrowWidth: 639,
    narrowHeadingSizes: ["h1": 1.625],
    quote: Quote(borderWidth: 3, borderColor: .border, paddingStart: 1),
    rule: Rule(width: 1, color: .border, margin: 2))
}

extension ThemeColor {
  static let heading = ThemeColor(light: RGBA(0.0581, 0.0582, 0.0772, 1), dark: RGBA(0.9596, 0.9598, 0.9687, 1))
  static let mutedForeground = ThemeColor(light: RGBA(0.3741, 0.3748, 0.4045, 1), dark: RGBA(0.6416, 0.6423, 0.6696, 1))
  static let foreground = ThemeColor(light: RGBA(0.1108, 0.111, 0.1315, 1), dark: RGBA(0.8939, 0.8943, 0.9089, 1))
  static let border = ThemeColor(light: RGBA(0.881, 0.8814, 0.8959, 1), dark: RGBA(0.187, 0.1874, 0.2051, 1))
}
