import { fileURLToPath } from "node:url";
import postcss from "postcss";
import { swiftRawString } from "./links";
import { swiftString } from "./swift";
import { ThemeColors, swiftRGBA } from "./typography";

export const DOCUMENT_HEADER_STYLE_PATH = new URL(
  "../Sources/TextKitEditor/WebDocumentHeaderStyle.swift",
  import.meta.url,
);

export const DOCUMENT_HEADER_SCRIPT_PATH = new URL(
  "../Sources/TextKitEditor/WebDocumentHeader.swift",
  import.meta.url,
);

/** The web's own header normalisation and property parsing, bundled. */
export async function swiftForDocumentHeaderScript(): Promise<string> {
  const build = await Bun.build({
    entrypoints: [
      fileURLToPath(new URL("document-header-entry.ts", import.meta.url)),
    ],
    target: "browser",
    format: "iife",
    minify: true,
  });
  if (!build.success)
    throw new AggregateError(build.logs, "Header bundle failed");
  return `// Generated by \`bun run codegen\`. Do not edit.\nlet documentHeaderScript = ${swiftRawString(((await build.outputs[0]?.text()) ?? "").trim())}\n`;
}

type RGBA = [number, number, number, number];

/**
 * How the web's document header shows the properties, subtitle, cover and
 * contents a document's root keeps, read from its stylesheets. Lengths are
 * in points, as the web's pixels, except where named as ems.
 */
export async function swiftForDocumentHeaderStyle(): Promise<string> {
  const read = (path: string) =>
    Bun.file(new URL(path, import.meta.url)).text();
  const css = postcss.parse(
    await read("../../lexidraw/src/styles/document.css"),
  );
  const colors = new ThemeColors(
    postcss.parse(await read("../../lexidraw/src/styles/globals.css")),
  );
  const header = await read(
    "../../lexidraw/src/app/documents/[documentId]/header/document-header.tsx",
  );

  const rules = (selector: string, within?: string) => {
    const found = new Map<string, string>();
    let matched = false;
    css.walkRules((rule) => {
      const scope =
        rule.parent?.type === "atrule"
          ? `${rule.parent.name} ${rule.parent.params}`
          : undefined;
      if (scope !== within) return;
      if (
        !rule.selectors
          .map((s) => s.replace(/\s+/g, " ").trim())
          .includes(selector)
      )
        return;
      matched = true;
      rule.walkDecls((decl) => {
        found.set(decl.prop, decl.value);
      });
    });
    if (!matched) throw new Error(`document.css has no rule for ${selector}`);
    return (property: string) => {
      const value = found.get(property);
      if (value === undefined)
        throw new Error(`${selector} sets no ${property}`);
      return value;
    };
  };
  const px = (text: string) => {
    const match = /^(-?[\d.]+)px$/.exec(text);
    if (!match?.[1]) throw new Error(`Not in pixels: ${text}`);
    return Number(match[1]);
  };
  const em = (text: string) => {
    const match = /^(-?[\d.]+)em$/.exec(text);
    if (!match?.[1]) throw new Error(`Not in ems: ${text}`);
    return Number(match[1]);
  };
  const plain = (text: string) => {
    const value = Number(text);
    if (text === "" || Number.isNaN(value))
      throw new Error(`Not a number: ${text}`);
    return value;
  };
  const parts = (text: string) => text.split(/\s+(?![^(]*\))/);
  const color = (text: string): [RGBA, RGBA] => {
    const name = colors.name(text).slice(1);
    const used = colors.used.find(([used]) => used === name);
    if (!used) throw new Error(`No theme colour ${text}`);
    return [used[1], used[2]];
  };
  // color-mix(in oklab, X p%, transparent) and color-mix(in oklab, X p%, Y).
  const mix = (text: string, own?: string): [RGBA, RGBA] => {
    const match =
      /^color-mix\(in oklab, (var\([\w-]+\)) (\d+)%, (transparent|var\([\w-]+\))\)$/.exec(
        text,
      );
    if (!match?.[1] || !match[2] || !match[3])
      throw new Error(`Not an oklab mix: ${text}`);
    const first = color(match[1] === "var(--status)" && own ? own : match[1]);
    const share = Number(match[2]) / 100;
    if (match[3] === "transparent")
      return first.map(([r, g, b, a]) => [r, g, b, a * share]) as [RGBA, RGBA];
    const second = color(match[3]);
    return [0, 1].map((theme) =>
      mixOklab(first[theme] as RGBA, second[theme] as RGBA, share),
    ) as [RGBA, RGBA];
  };

  const headerRule = rules(".document-header > *");
  if (headerRule("margin-inline") !== "auto")
    throw new Error("The header column changed shape");
  const cover = rules(".document-cover");
  const coverImage = rules(".document-cover img");
  const [aspectWidth, aspectHeight] = coverImage("aspect-ratio")
    .split("/")
    .map((part) => plain(part.trim()));
  const subtitle = rules(".document-subtitle");
  const [subtitleBefore, subtitleAfter] = parts(subtitle("margin-block"));
  const properties = rules(".document-properties");
  const [rowGap, columnGap] = parts(properties("gap"));
  if (properties("grid-template-columns") !== "max-content minmax(0, 1fr)")
    throw new Error("The property grid changed shape");
  const narrow = css.nodes.find(
    (node): node is postcss.AtRule =>
      node.type === "atrule" &&
      node.name === "container" &&
      /^\(max-width: \d+px\)$/.test(node.params) &&
      node.toString().includes(".document-properties"),
  );
  const narrowWidth = /(\d+)px/.exec(narrow?.params ?? "")?.[1];
  if (!narrowWidth) throw new Error("The narrow property grid changed shape");
  const narrowRule = (selector: string) =>
    rules(selector, `container ${narrow?.params}`);
  const term = rules(".document-property dt");
  const detail = rules(".document-property dd");
  const link = rules(".document-property dd a");
  const status = rules(".document-status");
  const [statusPaddingY, statusPaddingX] = parts(status("padding"));
  const statusKinds = [
    ...css
      .toString()
      .matchAll(
        /\.document-status:is\(([^)]*\)[^{]*)\{\s*--status: (var\([\w-]+\));/g,
      ),
  ].map((match) => ({
    names: [...(match[1] ?? "").matchAll(/data-status="([^"]+)"/g)].map(
      (name) => name[1] ?? "",
    ),
    color: match[2] ?? "",
  }));
  if (statusKinds.length === 0)
    throw new Error("The status kinds changed shape");
  const mention = rules(".document-mention");
  const [mentionPaddingY, mentionPaddingX] = parts(mention("padding"));
  const contents = rules(".document-contents");
  const contentsLabel = rules(".document-contents-label");
  const contentsItem = rules(".document-contents li");
  const contentsSubitem = rules('.document-contents li[data-level="h3"]');
  const label = /className="document-contents-label">([^<]+)</.exec(
    header,
  )?.[1];
  if (!label) throw new Error("The contents label changed shape");
  const statusDefault = status("--status");

  const theme = ([light, dark]: [RGBA, RGBA]) =>
    `ThemeColor(light: ${swiftRGBA(light)}, dark: ${swiftRGBA(dark)})`;
  const values: [string, number][] = [
    ["coverAfter", px(parts(cover("margin-block"))[1] ?? "")],
    ["coverAspect", (aspectWidth ?? 0) / (aspectHeight ?? 1)],
    [
      "coverMaximumViewportShare",
      plain(/^(\d+)svh$/.exec(coverImage("max-height"))?.[1] ?? "") / 100,
    ],
    ["coverRadius", px(coverImage("border-radius"))],
    ["subtitleSize", em(subtitle("font-size"))],
    ["subtitleLineHeight", plain(subtitle("line-height"))],
    ["subtitleBefore", em(subtitleBefore ?? "")],
    ["subtitleAfter", em(subtitleAfter ?? "")],
    ["propertyRowGap", px(rowGap ?? "")],
    ["propertyColumnGap", px(columnGap ?? "")],
    ["propertiesAfter", px(parts(properties("margin-block"))[1] ?? "")],
    ["narrowWidth", Number(narrowWidth)],
    ["narrowRowGap", plain(narrowRule(".document-properties")("row-gap"))],
    [
      "narrowValueAfter",
      px(narrowRule(".document-property dd")("margin-block-end")),
    ],
    ["termSize", px(term("font-size"))],
    ["termLineHeight", plain(term("line-height"))],
    ["valueSize", px(detail("font-size"))],
    ["valueLineHeight", plain(detail("line-height"))],
    ["valueGap", px(parts(detail("gap"))[1] ?? "")],
    [
      "statusPaddingY",
      px(statusPaddingY === "0" ? "0px" : (statusPaddingY ?? "")),
    ],
    ["statusPaddingX", px(statusPaddingX ?? "")],
    ["statusSize", px(status("font-size"))],
    ["statusWeight", plain(status("font-weight"))],
    ["statusLineHeight", plain(status("line-height"))],
    [
      "mentionPaddingY",
      px(mentionPaddingY === "0" ? "0px" : (mentionPaddingY ?? "")),
    ],
    ["mentionPaddingX", px(mentionPaddingX ?? "")],
    ["mentionRadius", px(mention("border-radius"))],
    ["mentionWeight", plain(mention("font-weight"))],
    ["contentsAfter", px(parts(contents("margin-block"))[1] ?? "")],
    ["contentsSize", px(contents("font-size"))],
    ["contentsLineHeight", plain(contents("line-height"))],
    ["contentsLabelSize", px(contentsLabel("font-size"))],
    ["contentsLabelWeight", plain(contentsLabel("font-weight"))],
    ["contentsLabelAfter", px(parts(contentsLabel("margin-block"))[1] ?? "")],
    ["contentsItemPadding", px(contentsItem("padding-block"))],
    ["contentsSubitemIndent", em(contentsSubitem("padding-inline-start"))],
    ["contentsSubitemSize", px(contentsSubitem("font-size"))],
  ];
  if (values.some(([, value]) => !Number.isFinite(value)))
    throw new Error("Unknown document header CSS shape");
  const statusColors = [
    ["", statusDefault],
    ...statusKinds.flatMap(({ names, color }) =>
      names.map((name) => [name, color] as const),
    ),
  ].map(
    ([name, own]) =>
      `${swiftString(name ?? "")}: (background: ${theme(mix(status("background"), own))}, foreground: ${theme(mix(status("color"), own))})`,
  );
  if (link("text-decoration") !== "underline")
    throw new Error("The property link changed shape");

  return `// Generated from document.css by apps/ios/codegen/document-header.ts.

enum WebDocumentHeaderStyle {
${values.map(([key, value]) => `  static let ${key}: Double = ${value}`).join("\n")}
  static let contentsLabel = ${swiftString(label)}
  static let coverBackground = ${theme(color(coverImage("background")))}
  static let subtitleColor = ${theme(color(subtitle("color")))}
  static let termColor = ${theme(color(term("color")))}
  static let linkColor = ${theme(color(link("color")))}
  static let contentsLabelColor = ${theme(color(contentsLabel("color")))}
  static let mentionBackground = ${theme(mix(mention("background")))}
  static let mentionForeground = ${theme(mix(mention("color")))}
  /// By lowercased status, with "" for any other.
  static let statusColors: [String: (background: ThemeColor, foreground: ThemeColor)] = [
    ${statusColors.join(",\n    ")},
  ]
}
`;
}

function toLinear(channel: number) {
  return channel <= 0.04045
    ? channel / 12.92
    : ((channel + 0.055) / 1.055) ** 2.4;
}

function fromLinear(channel: number) {
  const value =
    channel <= 0.0031308
      ? channel * 12.92
      : 1.055 * channel ** (1 / 2.4) - 0.055;
  return Math.max(0, Math.min(1, value));
}

function oklab([r, g, b]: RGBA): [number, number, number] {
  // Mapping the three RGB channels preserves tuple length.
  const [lr, lg, lb] = [r, g, b].map(toLinear) as [number, number, number];
  const l = Math.cbrt(
    0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb,
  );
  const m = Math.cbrt(
    0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb,
  );
  const s = Math.cbrt(
    0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb,
  );
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
}

function srgb([L, a, b]: [number, number, number]): [number, number, number] {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  // Mapping the three computed channels preserves tuple length.
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ].map(fromLinear) as [number, number, number];
}

/** CSS color-mix in oklab of two opaque colours, `share` of the first. */
function mixOklab(first: RGBA, second: RGBA, share: number): RGBA {
  if (first[3] !== 1 || second[3] !== 1)
    throw new Error("Mixing translucent theme colours isn't read yet");
  const [x, y] = [oklab(first), oklab(second)];
  return [
    ...srgb(
      // Exactly three channel indices produce the color tuple.
      [0, 1, 2].map((i) => (x[i] ?? 0) * share + (y[i] ?? 0) * (1 - share)) as [
        number,
        number,
        number,
      ],
    ),
    1,
  ];
}
