import { fileURLToPath } from "node:url";
import postcss from "postcss";
import { swiftRawString } from "./links";

export const DOCUMENT_SETTINGS_PATH = fileURLToPath(
  new URL("../Sources/LexidrawKit/WebDocumentSettings.swift", import.meta.url),
);

export async function swiftForDocumentSettings() {
  const css = postcss.parse(
    await Bun.file(
      new URL("../../lexidraw/src/styles/document.css", import.meta.url),
    ).text(),
  );
  const rules: { languages: string[]; variables: Record<string, string> }[] =
    [];
  css.walkRules((rule) => {
    const variables: Record<string, string> = {};
    rule.walkDecls((decl) => {
      if (/^--(?:font-|doc-(?:font-|cjk-|emoji$))/.test(decl.prop))
        variables[decl.prop] = decl.value;
    });
    if (!Object.keys(variables).length) return;
    const languages = rule.selectors.flatMap((selector) => {
      const match =
        /^\.document-(?:typography|content)(?::lang\(([a-zA-Z-]+)\))?$/.exec(
          selector,
        );
      if (!match) throw new Error(`Unported font selector: ${selector}`);
      return match[1] ? [match[1].toLowerCase()] : [];
    });
    rules.push({ languages, variables });
  });
  const source = await Bun.file(
    new URL("../../lexidraw/src/lib/fonts.ts", import.meta.url),
  ).text();
  const fonts: Record<string, string> = {};
  for (const match of source.matchAll(/=\s*([A-Za-z_]+)\(\{([\s\S]*?)\}\)/g)) {
    const variable = /variable:\s*"(--font-[a-z-]+)"/.exec(match[2] ?? "")?.[1];
    if (!variable || !match[1])
      throw new Error("Unported Next font configuration");
    fonts[variable] = JSON.stringify(match[1].replaceAll("_", " "));
  }
  if (!Object.keys(fonts).length || !rules.length)
    throw new Error("Document fonts were not found");
  const build = await Bun.build({
    entrypoints: [
      fileURLToPath(new URL("document-settings.ts", import.meta.url)),
    ],
    target: "browser",
    format: "iife",
    minify: true,
    define: {
      DOCUMENT_FONT_RULES: JSON.stringify(rules),
      DOCUMENT_NEXT_FONTS: JSON.stringify(fonts),
    },
  });
  if (!build.success || !build.outputs[0])
    throw new AggregateError(build.logs, "Document settings bundling failed");
  return `// Generated by \`bun run codegen\`. Do not edit.\nlet documentSettingsScript = ${swiftRawString((await build.outputs[0].text()).trim())}\n`;
}
