import { fileURLToPath } from "node:url";

export const DRAWING_FILES_PATH = fileURLToPath(
  new URL("../Sources/LexidrawJSON/DrawingFiles.swift", import.meta.url),
);

export const OPENAPI_PATH = fileURLToPath(
  new URL("../Sources/LexidrawKit/openapi.json", import.meta.url),
);

/** The part of the committed OpenAPI document the types are read from. */
type OpenAPI = {
  paths: {
    "/drawings/{id}/files": {
      get: {
        responses: {
          "200": {
            content: {
              "application/json": {
                schema: {
                  properties: {
                    files: {
                      items: { properties: { mimeType: { enum: string[] } } };
                    };
                  };
                };
              };
            };
          };
        };
      };
    };
  };
};

/**
 * The file types a drawing stores, as the server lists them, and the largest
 * file it stores, in Swift, for the app and the editor to hold to the same.
 */
export function swiftForDrawingFiles(
  openapi: OpenAPI,
  maxBytes: number,
): string {
  const types =
    openapi.paths["/drawings/{id}/files"].get.responses["200"].content[
      "application/json"
    ].schema.properties.files.items.properties.mimeType.enum;
  const lines = [
    "// Generated by `bun run codegen` in apps/ios. Don't edit it.",
    "",
    "/// A type of file a drawing stores.",
    "public enum DrawingFileType: String, CaseIterable, Sendable {",
    ...types.map((type) => `  case ${caseName(type)} = "${type}"`),
    "}",
    "",
    "/// `MAX_DRAWING_FILE_BYTES`: the largest file a drawing stores, in bytes.",
    `public let maxDrawingFileBytes = ${maxBytes}`,
  ];
  return `${lines.join("\n")}\n`;
}

/** `image/svg+xml` as `svg`. */
function caseName(type: string): string {
  const subtype = type.split("/")[1]?.split("+")[0];
  if (!subtype || !/^[a-z]+$/.test(subtype)) {
    throw new Error(`No Swift case name for ${type}`);
  }
  return subtype;
}
