import { readFileSync } from "node:fs";

const directory = new URL(
  "../../lexidraw/src/app/documents/[documentId]/",
  import.meta.url,
);
type Step = {
  comparison: ">" | ">=" | "<" | "<=";
  bound: string;
  operation: "=" | "+=" | "-=";
  value: string;
};

export function fontSizing() {
  const context = readFileSync(
    new URL("context/toolbar-context.tsx", directory),
    "utf8",
  );
  const values = new Map<string, number>();
  for (const name of [
    "MIN_ALLOWED_FONT_SIZE",
    "MAX_ALLOWED_FONT_SIZE",
    "DEFAULT_FONT_SIZE",
  ]) {
    const match = context.match(new RegExp(`export const ${name} = (\\d+);`));
    if (!match?.[1]) throw new Error(`Unknown ${name} shape`);
    values.set(name, Number(match[1]));
  }
  const value = (literal: string): number => {
    const result = /^\d+$/.test(literal)
      ? Number(literal)
      : values.get(literal);
    if (result === undefined)
      throw new Error(`Unknown font-size value ${literal}`);
    return result;
  };
  const source = readFileSync(
    new URL("plugins/ToolbarPlugin/utils.ts", directory),
    "utf8",
  );
  const branches = (direction: "increment" | "decrement") => {
    const branch = source.match(
      new RegExp(
        `case UpdateFontSizeType\\.${direction}:\\s*switch \\(true\\) \\{([\\s\\S]*?)\\}\\s*break;`,
      ),
    )?.[1];
    if (!branch) throw new Error(`Unknown font-size ${direction} shape`);
    const pattern =
      /case currentFontSize (>=|<=|>|<) (\w+):\s*updatedFontSize (=|\+=|-=) (\w+);\s*break;/g;
    const steps: Step[] = [...branch.matchAll(pattern)].map((match) => ({
      comparison: match[1] as Step["comparison"],
      bound: match[2]!,
      operation: match[3] as Step["operation"],
      value: match[4]!,
    }));
    const remaining = branch.replace(pattern, "").trim();
    const fallback = remaining.match(
      /^default:\s*updatedFontSize = (\w+);\s*break;$/,
    )?.[1];
    if (!steps.length || !fallback)
      throw new Error(`Unknown font-size ${direction} cases`);
    for (const step of steps) {
      value(step.bound);
      value(step.value);
    }
    return { steps, fallback };
  };
  const increment = branches("increment");
  const decrement = branches("decrement");
  const evaluate = (branch: ReturnType<typeof branches>, current: number) => {
    for (const step of branch.steps) {
      const bound = value(step.bound);
      const matches =
        step.comparison === ">"
          ? current > bound
          : step.comparison === ">="
            ? current >= bound
            : step.comparison === "<"
              ? current < bound
              : current <= bound;
      if (matches)
        return step.operation === "="
          ? value(step.value)
          : current + (step.operation === "+=" ? 1 : -1) * value(step.value);
    }
    return value(branch.fallback);
  };
  const swift = (branch: ReturnType<typeof branches>) =>
    branch.steps
      .map(
        (step) =>
          `    if current ${step.comparison} ${value(step.bound)} { return ${step.operation === "=" ? value(step.value) : `current ${step.operation === "+=" ? "+" : "-"} ${value(step.value)}`} }`,
      )
      .join("\n") + `\n    return ${value(branch.fallback)}`;
  return {
    default: value("DEFAULT_FONT_SIZE"),
    minimum: value("MIN_ALLOWED_FONT_SIZE"),
    maximum: value("MAX_ALLOWED_FONT_SIZE"),
    increment: (current: number) => evaluate(increment, current),
    decrement: (current: number) => evaluate(decrement, current),
    reference: (() => {
      const enumeration = source.match(
        / {2}enum UpdateFontSizeType \{[\s\S]*?\n {2}\}/,
      )?.[0];
      const calculation = source.match(
        / {2}const calculateNextFontSize = [\s\S]*?\n {2}\};/,
      )?.[0];
      if (!enumeration || !calculation)
        throw new Error("Unknown web font-size calculation shape");
      return `// Generated from the original web toolbar calculation.\n${[...values].map(([name, number]) => `export const ${name} = ${number};`).join("\n")}\n${enumeration}\n${calculation}\nexport function nextFontSize(current: number, increase: boolean): number {\n  return calculateNextFontSize(current, increase ? UpdateFontSizeType.increment : UpdateFontSizeType.decrement);\n}\n`;
    })(),
    swift: `// Generated by codegen/font-sizing.ts from the web toolbar.\npublic enum WebFontSizing {\n  public static let defaultSize: Double = ${value("DEFAULT_FONT_SIZE")}\n  public static func increment(_ current: Double) -> Double {\n${swift(increment)}\n  }\n  public static func decrement(_ current: Double) -> Double {\n${swift(decrement)}\n  }\n}\n`,
  };
}
