import { fileURLToPath } from "node:url";
import { swiftRawString } from "./links";
export const HTML_IMPORT_PATH = fileURLToPath(
  new URL("../Sources/LexicalSwift/HTMLConfiguration.swift", import.meta.url),
);
export async function swiftForHTMLImport(): Promise<string> {
  const build = await Bun.build({
    entrypoints: [fileURLToPath(new URL("html-import.ts", import.meta.url))],
    target: "browser",
    format: "iife",
    minify: true,
    define: { "process.env.NODE_ENV": JSON.stringify("development") },
  });
  if (!build.success || !build.outputs[0])
    throw new AggregateError(build.logs, "HTML importer bundling failed");
  const script = (await build.outputs[0].text())
    .split("\n")
    .filter((line) => !/^\s*\/\/ \S+\.[jt]s$/.test(line))
    .join("\n")
    .trimEnd();
  return `// Generated by \`bun run codegen\` in apps/ios. Don't edit it.\nlet htmlImportScript = ${swiftRawString(script)}\n`;
}
