import { fileURLToPath } from "node:url";
import {
  AUTOLINK_EMAIL_REGEX,
  AUTOLINK_URL_REGEX,
  EDITOR_NAMESPACE,
  LINK_URL_REGEX,
} from "@packages/lexical-nodes/links";

export const LINKS_PATH = fileURLToPath(
  new URL("../Sources/LexicalSwift/LinkConfiguration.swift", import.meta.url),
);

/**
 * The document editor's namespace and the patterns its link plugins match
 * text with, in Swift. The patterns stay JavaScript regular expression
 * literals, for LexicalSwift to run as JavaScript runs them.
 */
export function swiftForLinks(): string {
  const lines = [
    "// Generated by `bun run codegen` in apps/ios. Don't edit it.",
    "",
    "/// `EDITOR_NAMESPACE`: what a clipboard payload of nodes has to carry to",
    "/// paste as nodes.",
    `public let editorNamespace = ${swiftRawString(EDITOR_NAMESPACE)}`,
    "",
    "/// The link patterns in `packages/lexical-nodes/src/links.ts`.",
    "enum LinkPatterns {",
    `  static let autoLinkURL = ${swiftRawString(String(AUTOLINK_URL_REGEX))}`,
    `  static let autoLinkEmail = ${swiftRawString(String(AUTOLINK_EMAIL_REGEX))}`,
    `  static let linkURL = ${swiftRawString(String(LINK_URL_REGEX))}`,
    "}",
  ];
  return `${lines.join("\n")}\n`;
}

/** `text` as a Swift raw string literal. */
export function swiftRawString(text: string): string {
  let hashes = "#";
  while (text.includes(`"${hashes}`)) hashes += "#";
  return `${hashes}"${text}"${hashes}`;
}
