import { fileURLToPath } from "node:url";
import { EDITOR_NAMESPACE } from "@packages/lexical-nodes/links";

export const LINKS_PATH = fileURLToPath(
  new URL("../Sources/LexicalSwift/LinkConfiguration.swift", import.meta.url),
);

const SCRIPT_ENTRY = fileURLToPath(
  new URL("./link-configuration.ts", import.meta.url),
);

/**
 * The document editor's namespace, and its autolink matchers and
 * `validateUrl` bundled as a script, for LexicalSwift to run the web's own
 * code where the web's link plugins call it.
 */
export async function swiftForLinks(): Promise<string> {
  const build = await Bun.build({
    entrypoints: [SCRIPT_ENTRY],
    format: "iife",
    target: "browser",
  });
  const [output] = build.outputs;
  if (!build.success || !output) {
    throw new AggregateError(build.logs, "bundling failed");
  }
  // The bundler heads each module with its path, which is the package
  // store's on this machine.
  const script = (await output.text())
    .split("\n")
    .filter((line) => !/^\s*\/\/ \S+\.[jt]s$/.test(line))
    .join("\n")
    .trimEnd();
  const lines = [
    "// Generated by `bun run codegen` in apps/ios. Don't edit it.",
    "",
    "/// `EDITOR_NAMESPACE`: what a clipboard payload of nodes has to carry to",
    "/// paste as nodes.",
    `public let editorNamespace = ${swiftRawString(EDITOR_NAMESPACE)}`,
    "",
    "/// `packages/lexical-nodes/src/links.ts`, bundled: it sets",
    "/// `linkConfiguration` to the web editor's autolink `matchers` and",
    "/// `validateUrl`.",
    `let linkConfigurationScript = ${swiftRawString(script)}`,
  ];
  return `${lines.join("\n")}\n`;
}

/** `text` as a Swift raw string literal. */
export function swiftRawString(text: string): string {
  let hashes = "#";
  while (text.includes(`"${hashes}`) || text.includes(`\\${hashes}`)) {
    hashes += "#";
  }
  return text.includes("\n")
    ? `${hashes}"""\n${text}\n"""${hashes}`
    : `${hashes}"${text}"${hashes}`;
}
