import { fileURLToPath } from "node:url";
import {
  EDITOR_NAMESPACE,
  SUPPORTED_URL_PROTOCOLS,
} from "@packages/lexical-nodes/links";

export const LINKS_PATH = fileURLToPath(
  new URL("../Sources/LexicalSwift/LinkConfiguration.swift", import.meta.url),
);

export const LINK_PROTOCOLS_PATH = fileURLToPath(
  new URL("../Sources/TextKitEditor/LinkProtocols.swift", import.meta.url),
);

const SCRIPT_ENTRY = fileURLToPath(
  new URL("./link-configuration.ts", import.meta.url),
);

/**
 * The document editor's namespace, and its autolink matchers, `validateUrl`
 * and `sanitizeUrl` bundled as a script, for LexicalSwift to run the web's own
 * code where the web's link plugins call it.
 */
export async function swiftForLinks(): Promise<string> {
  const build = await Bun.build({
    entrypoints: [SCRIPT_ENTRY],
    format: "iife",
    target: "browser",
  });
  const [output] = build.outputs;
  if (!build.success || !output) {
    throw new AggregateError(build.logs, "bundling failed");
  }
  // The bundler heads each module with its path, which is the package
  // store's on this machine.
  const script = (await output.text())
    .split("\n")
    .filter((line) => !/^\s*\/\/ \S+\.[jt]s$/.test(line))
    .join("\n")
    .trimEnd();
  const lines = [
    "// Generated by `bun run codegen` in apps/ios. Don't edit it.",
    "",
    "/// `EDITOR_NAMESPACE`: what a clipboard payload of nodes has to carry to",
    "/// paste as nodes.",
    `public let editorNamespace = ${swiftRawString(EDITOR_NAMESPACE)}`,
    "",
    "/// `packages/lexical-nodes/src/links.ts`, bundled with whatwg-url for",
    "/// its `URL`: it sets `linkConfiguration` to the web editor's autolink",
    "/// `matchers`, `validateUrl` and `sanitizeUrl`.",
    `let linkConfigurationScript = ${swiftRawString(script)}`,
  ];
  return `${lines.join("\n")}\n`;
}

/** The protocols the web opens a link with, for the iOS editor to offer to open. */
export function swiftForLinkProtocols(): string {
  const protocols = [...SUPPORTED_URL_PROTOCOLS].map((protocol) =>
    JSON.stringify(protocol),
  );
  const lines = [
    "// Generated by `bun run codegen` in apps/ios. Don't edit it.",
    "",
    "/// `SUPPORTED_URL_PROTOCOLS` in `packages/lexical-nodes/src/links.ts`.",
    `let supportedURLProtocols: Set<String> = [${protocols.join(", ")}]`,
  ];
  return `${lines.join("\n")}\n`;
}

/** `text` as a Swift raw string literal. */
export function swiftRawString(text: string): string {
  let hashes = "#";
  while (text.includes(`"${hashes}`) || text.includes(`\\${hashes}`)) {
    hashes += "#";
  }
  return text.includes("\n")
    ? `${hashes}"""\n${text}\n"""${hashes}`
    : `${hashes}"${text}"${hashes}`;
}
