import { fileURLToPath } from "node:url";
import * as lexicalMarkdown from "@lexical/markdown";
import type { Transformer } from "@lexical/markdown";
import * as blockTransformers from "@packages/lexical-nodes/block-transformers";
import * as decoratorTransformers from "@packages/lexical-nodes/decorator-transformers";
import * as footnoteTransformers from "@packages/lexical-nodes/footnote-transformers";
import * as webTransformers from "@packages/lexical-nodes/transformers";
import { swiftString } from "./swift";

export const MARKDOWN_TRANSFORMERS_PATH = fileURLToPath(
  new URL(
    "../Sources/LexicalSwift/MarkdownTransformers.swift",
    import.meta.url,
  ),
);

const MODULES = [
  lexicalMarkdown,
  webTransformers,
  blockTransformers,
  decoratorTransformers,
  footnoteTransformers,
];

/**
 * The transformers @lexical/markdown and the web editor export, by name, and
 * those the web editor's `createXTransformer` functions make, as `X`.
 */
const EXPORTED = [
  ...MODULES.flatMap((module) => Object.entries(module)),
  ...MODULES.flatMap((module) =>
    Object.entries(module).flatMap(([name, create]) => {
      const made = name.match(/^create(\w+)Transformer$/)?.[1];
      if (!made || typeof create !== "function") return [];
      return [[snakeCase(made), create(() => [])]];
    }),
  ),
].filter((entry): entry is [string, Transformer] => isTransformer(entry[1]));

/** Patterns the web's transformers match with besides their own. */
export const MARKDOWN_PATTERNS = {
  TABLE_ROW_DIVIDER_REG_EXP: webTransformers.TABLE_ROW_DIVIDER_REG_EXP,
  FENCE: blockTransformers.FENCE,
  ADMONITION_END: blockTransformers.ADMONITION_END,
  DETAILS_OPEN: blockTransformers.DETAILS_OPEN,
  DETAILS_CLOSE: blockTransformers.DETAILS_CLOSE,
  COLUMNS_CLOSE: blockTransformers.COLUMNS_CLOSE,
};

/**
 * The web editor's markdown transformers in Swift, in the order they run, for
 * LexicalSwift's shortcuts to run as `registerMarkdownShortcuts` does, and
 * `patterns` by the names they're exported by. JavaScriptCore evaluates their
 * regular expressions, so they match as the web's do.
 */
export function swiftForMarkdownTransformers(
  transformers: Transformer[],
  patterns: Record<string, RegExp> = {},
): string {
  const names = new Set<string>();
  const entries = transformers.map((transformer) => {
    const name = exportedName(transformer);
    names.add(name);
    return `    ${swiftForTransformer(transformer, name)},`;
  });
  const lines = [
    "// Generated by `bun run codegen` in apps/ios. Don't edit it.",
    "",
    "extension MarkdownTransformer {",
    "  /// `createTransformers()` in @packages/lexical-nodes: the web editor's",
    "  /// markdown transformers, in the order it runs them.",
    "  static let web: [MarkdownTransformer] = [",
    ...entries,
    "  ]",
    "",
    "  /// The name @lexical/markdown or the web editor exports a transformer by.",
    "  enum Name: String, Sendable {",
    ...[...names].map((name) => `    case ${camelCase(name)} = "${name}"`),
    "  }",
    ...Object.entries(patterns).flatMap(([name, regExp]) => [
      "",
      `  /// \`${name}\` in @packages/lexical-nodes.`,
      `  static let ${camelCase(name)} = ${swiftForPattern(regExp)}`,
    ]),
    "}",
  ];
  return `${lines.join("\n")}\n`;
}

function swiftForTransformer(transformer: Transformer, name: string): string {
  const fields = [`name: .${camelCase(name)}`];
  switch (transformer.type) {
    case "element":
      fields.push(`regExp: ${swiftForRegExp(transformer.regExp)}`);
      if (transformer.triggerOnEnter) fields.push("triggerOnEnter: true");
      fields.push(swiftForMakes(transformer));
      return `MarkdownTransformer(kind: .element, ${fields.join(", ")})`;
    case "multiline-element": {
      fields.push(`regExp: ${swiftForRegExp(transformer.regExpStart)}`);
      const end = transformer.regExpEnd;
      if (end) {
        fields.push(
          `regExpEnd: ${swiftForRegExp("regExp" in end ? end.regExp : end)}`,
        );
      }
      if (end && (!("optional" in end) || !end.optional)) {
        fields.push("isEndRequired: true");
      }
      fields.push(swiftForMakes(transformer));
      return `MarkdownTransformer(kind: .multilineElement, ${fields.join(", ")})`;
    }
    case "text-match":
      if (transformer.getEndIndex) {
        throw new Error(
          `The text match ${name} ends its match in code, which Swift can't run`,
        );
      }
      if (transformer.regExp && transformer.replace) {
        fields.push(`regExp: ${swiftForRegExp(transformer.regExp)}`);
      }
      if (transformer.importRegExp && transformer.replace) {
        fields.push(
          `importRegExp: ${swiftForRegExp(transformer.importRegExp)}`,
        );
      }
      if (transformer.trigger !== undefined) {
        fields.push(`trigger: ${swiftString(transformer.trigger)}`);
      }
      fields.push(swiftForMakes(transformer));
      return `MarkdownTransformer(kind: .textMatch, ${fields.join(", ")})`;
    case "text-format":
      fields.push(
        `tag: ${swiftString(transformer.tag)}`,
        `formats: [${transformer.format.map((format) => `.${format}`).join(", ")}]`,
      );
      if (transformer.intraword === false) fields.push("isIntraword: false");
      return `MarkdownTransformer(kind: .textFormat, ${fields.join(", ")})`;
  }
}

/**
 * A transformer's name, by its identity or, for one that copies another or
 * that a `createXTransformer` made, by its type and pattern.
 */
function exportedName(transformer: Transformer): string {
  const exact = EXPORTED.find(([, exported]) => exported === transformer);
  if (exact) return exact[0];
  const source = matchSource(transformer);
  const alike = EXPORTED.find(
    ([, exported]) =>
      source !== undefined &&
      exported.type === transformer.type &&
      matchSource(exported) === source,
  );
  if (alike) return alike[0];
  throw new Error(
    `No package exports the transformer ${source ?? transformer.type}`,
  );
}

function matchSource(transformer: Transformer): string | undefined {
  const regExp =
    transformer.type === "multiline-element"
      ? transformer.regExpStart
      : transformer.type === "text-format"
        ? undefined
        : transformer.regExp;
  return regExp && `/${regExp.source}/`;
}

/** The node types a transformer's `replace` can make, its `dependencies`. */
function swiftForMakes(
  transformer: Exclude<Transformer, { type: "text-format" }>,
): string {
  const types = transformer.dependencies.map((node) => node.getType());
  return `makes: [${types.map(swiftString).join(", ")}]`;
}

function isTransformer(value: unknown): value is Transformer {
  return (
    typeof value === "object" &&
    value !== null &&
    "type" in value &&
    typeof value.type === "string"
  );
}

/** A pattern matched once, which can't depend on where it last matched. */
export function swiftForRegExp(regExp: RegExp): string {
  if (regExp.global || regExp.sticky) {
    throw new Error(
      `/${regExp.source}/${regExp.flags} keeps where it last matched, which a single match can't depend on`,
    );
  }
  return swiftForPattern(regExp);
}

/** A pattern, which one that's global counts matches with. */
function swiftForPattern(regExp: RegExp): string {
  if (regExp.sticky) {
    throw new Error(
      `/${regExp.source}/${regExp.flags} matches only where it last matched`,
    );
  }
  return `JSRegExp(${swiftString(regExp.source)}, flags: ${swiftString(regExp.flags)})`;
}

/** `Callout` as `CALLOUT`, `FootnoteReference` as `FOOTNOTE_REFERENCE`. */
function snakeCase(name: string): string {
  return name.replace(/(?<=[a-z])(?=[A-Z])/g, "_").toUpperCase();
}

/** `UNORDERED_LIST` as `unorderedList`. */
function camelCase(name: string): string {
  return name
    .toLowerCase()
    .replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase());
}
