import { fileURLToPath } from "node:url";
import { EDITOR_NAMESPACE } from "@packages/lexical-nodes/links";
import { MEDIA_LINK_BASES } from "@packages/lexical-nodes/media-links";

export const MEDIA_LINKS_PATH = fileURLToPath(
  new URL("../Sources/TextKitEditor/MediaLinks.swift", import.meta.url),
);
export function swiftForMediaLinks(): string {
  return `// Generated by apps/ios/codegen/media.ts. Do not edit.\nimport Foundation\n\nenum MediaLinks {\n  static let namespace = ${JSON.stringify(EDITOR_NAMESPACE)}\n${Object.entries(
    MEDIA_LINK_BASES,
  )
    .map(([type, base]) => `  static let ${type} = ${JSON.stringify(base)}`)
    .join("\n")}\n}\n`;
}
