import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { swiftRawString } from "./links";

export const SHORTCUTS_PATH = fileURLToPath(
  new URL("../Sources/TextKitEditor/KeyboardShortcuts.swift", import.meta.url),
);
const WEB_SHORTCUTS_PATH = fileURLToPath(
  new URL(
    "../../lexidraw/src/app/documents/[documentId]/plugins/ShortcutsPlugin/shortcuts.ts",
    import.meta.url,
  ),
);

export type ShortcutBinding = {
  action: string;
  input: string;
  command: boolean;
  shift: boolean;
  alternate: boolean;
};

type ShortcutEvent = {
  code: string;
  metaKey: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  altKey: boolean;
};

export function blockTypes(): { type: string; label: string }[] {
  const path = new URL(
    "../../lexidraw/src/app/documents/[documentId]/plugins/ToolbarPlugin/block-format.tsx",
    import.meta.url,
  );
  const source = readFileSync(path, "utf8").match(
    /export const BLOCK_TYPES = \[([\s\S]*?)\] as const satisfies/,
  );
  if (!source?.[1]) throw new Error("Unknown block choices shape");
  const choices: { type: string; label: string }[] = [];
  for (const entry of source[1].matchAll(/\{([^{}]*)\}/g)) {
    const match = entry[1]?.match(
      /^\s*type:\s*("(?:[^"\\]|\\.)*"),\s*label:\s*("(?:[^"\\]|\\.)*"),\s*icon:\s*\w+,?\s*(?:shortcut:\s*"[^"]*",?\s*)?(?:toggle:\s*"[^"]*",?\s*)?$/,
    );
    if (!match?.[1] || !match[2]) throw new Error("Unknown block choice shape");
    choices.push({ type: JSON.parse(match[1]), label: JSON.parse(match[2]) });
  }
  if (!choices.length) throw new Error("No web block choices");
  return choices;
}

export function shortcutBindings(): ShortcutBinding[] {
  const source = readFileSync(WEB_SHORTCUTS_PATH, "utf8").split(
    "export function useShortcuts() {",
  )[1];
  if (!source) throw new Error("Unknown web shortcut factory shape");
  const codes = new Set(Array.from({ length: 10 }, (_, n) => `Digit${n}`));
  for (const match of source.matchAll(
    /\/\/[^\n]*|\/\*[\s\S]*?\*\/|"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|`(?:[^`\\]|\\.)*`/g,
  )) {
    const token = match[0];
    if (token.startsWith("/")) continue;
    if (!token.startsWith('"'))
      throw new Error("Unknown shortcut string shape");
    const code: string = JSON.parse(token);
    if (/^\d?$/.test(code)) continue;
    nativeInput(code);
    codes.add(code);
  }
  const bindings = new Map<string, ShortcutBinding>();
  const script = new Bun.Transpiler({ loader: "ts" }).transformSync(
    `function shortcuts() {${source}`,
  );
  const predicates: unknown = new Function(
    "IS_APPLE",
    `${script}\nreturn shortcuts();`,
  )(true);
  if (!predicates || typeof predicates !== "object")
    throw new Error("Unknown shortcut predicates shape");
  for (const [predicateName, predicate] of Object.entries(predicates)) {
    if (typeof predicate !== "function")
      throw new Error(`Unknown shortcut function ${predicateName}`);
    if (!/^is[A-Z]\w+$/.test(predicateName))
      throw new Error(`Unknown shortcut predicate ${predicateName}`);
    const name = predicateName.slice(2);
    const action = name[0]?.toLowerCase() + name.slice(1);
    let matches = 0;
    for (const code of [...codes].sort()) {
      for (const command of [false, true])
        for (const shift of [false, true])
          for (const alternate of [false, true]) {
            const event = {
              code,
              metaKey: command,
              ctrlKey: command,
              shiftKey: shift,
              altKey: alternate,
            } satisfies ShortcutEvent;
            const matched: unknown = predicate(event);
            if (typeof matched !== "boolean")
              throw new Error(`Nonboolean shortcut ${predicateName}`);
            if (!matched) continue;
            const binding = {
              action,
              input: nativeInput(code),
              command,
              shift,
              alternate,
            };
            bindings.set(JSON.stringify(binding), binding);
            matches++;
          }
    }
    if (!matches) throw new Error(`No native mapping for ${predicateName}`);
  }
  return [...bindings.values()];
}

export function nativeInput(code: string): string {
  if (/^Key[A-Z]$/.test(code)) return code.slice(3).toLowerCase();
  if (/^(Digit|Numpad)\d$/.test(code)) return code.slice(-1);
  const punctuation: Record<string, string> = {
    BracketLeft: "[",
    BracketRight: "]",
    Comma: ",",
    Period: ".",
    Backslash: "\\",
  };
  const input = punctuation[code];
  if (input === undefined) throw new Error(`Unknown keyboard code ${code}`);
  return input;
}

export function swiftForShortcuts(): string {
  const bindings = shortcutBindings();
  const actions = [...new Set(bindings.map(({ action }) => action))];
  const lines = [
    "// Generated by `bun run codegen` in apps/ios. Don't edit it.",
    "#if canImport(UIKit)",
    "import UIKit",
    "",
    "enum WebShortcutAction: String {",
    ...actions.map(
      (action) => `  case ${action === "subscript" ? "`subscript`" : action}`,
    ),
    "}",
    "",
    "struct WebKeyboardShortcut {",
    "  let input: String",
    "  let modifiers: UIKeyModifierFlags",
    "  let action: WebShortcutAction",
    "}",
    "",
    "let webKeyboardShortcuts: [WebKeyboardShortcut] = [",
  ];
  for (const binding of bindings) {
    const modifiers = [
      binding.command ? ".command" : null,
      binding.shift ? ".shift" : null,
      binding.alternate ? ".alternate" : null,
    ]
      .filter(Boolean)
      .join(", ");
    lines.push(
      `  WebKeyboardShortcut(input: ${swiftRawString(binding.input)}, modifiers: [${modifiers}], action: .${binding.action}),`,
    );
  }
  lines.push(
    "]",
    "",
    "struct WebBlockChoice {",
    "  let type: String",
    "  let label: String",
    "}",
    "",
    "let webBlockChoices: [WebBlockChoice] = [",
  );
  for (const choice of blockTypes())
    lines.push(
      `  WebBlockChoice(type: ${swiftRawString(choice.type)}, label: ${swiftRawString(choice.label)}),`,
    );
  lines.push("]", "#endif", "");
  return lines.join("\n");
}
