import { fileURLToPath } from "node:url";
import {
  byCodeUnits,
  type FieldType,
  type NodeDescription,
  type NodeSchema,
  type NodeTraits,
  type Trait,
} from "@packages/lexical-nodes/node-schema";

export const SERIALIZED_NODES_PATH = fileURLToPath(
  new URL("../Sources/LexicalSwift/SerializedNodes.swift", import.meta.url),
);

/**
 * Enum type names where a field's name doesn't give one: the field takes
 * different values on different nodes, or the name alone would be vague.
 * Keyed by the enum's non-null values.
 */
const ENUM_NAMES: Record<string, string> = {
  [enumSignature(["", "left", "start", "center", "right", "end", "justify"])]:
    "ElementFormat",
  [enumSignature(["normal", "token", "segmented"])]: "TextMode",
  [enumSignature(["normal"])]: "TabMode",
  [enumSignature(["h1", "h2", "h3", "h4", "h5", "h6"])]: "HeadingTag",
  [enumSignature(["ul", "ol"])]: "ListTag",
  [enumSignature(["comment"])]: "CommentType",
  [enumSignature(["thread"])]: "ThreadType",
  [enumSignature(["note", "tip", "important", "warning", "caution"])]:
    "CalloutKind",
  [enumSignature([
    "pink",
    "yellow",
    "green",
    "blue",
    "red",
    "orange",
    "purple",
    "gray",
  ])]: "StickyNoteColor",
};

/**
 * Struct names where a field's name doesn't give a good one, keyed by the
 * object's path (`poll.options[]`) or, for every object under a field of
 * that name, by the field's name.
 */
const OBJECT_NAMES: Record<string, string> = {
  caption: "NestedEditor",
  "thread.thread": "CommentThread",
  "thread.thread.comments[]": "Comment",
  "poll.options[]": "PollOption",
};

/** Names a payload's own members take, which no field may reuse. */
const RESERVED_MEMBERS = new Set(["children", "json", "type", "unknownFields"]);

/** Names a declared object's own members take. */
const RESERVED_OBJECT_MEMBERS = new Set(["json", "unknownFields"]);

const SWIFT_KEYWORDS = new Set(
  "associatedtype class deinit enum extension fileprivate func import init inout internal let open operator private precedencegroup protocol public rethrows static struct subscript typealias var break case catch continue default defer do else fallthrough for guard if in repeat return throw switch where while Any as await false is nil self Self super throws true try".split(
    " ",
  ),
);

type ObjectType = Extract<FieldType, { kind: "object" }>;

/** The Swift names of enums, by signature, and of objects, by path. */
type Names = { enums: Map<string, string>; objects: Map<string, string> };

/** The Swift payload types for every declared node in `schema`. */
export function swiftForNodeSchema(schema: NodeSchema): string {
  const objects = objectTypes(schema.nodes);
  const names: Names = {
    enums: enumNames(schema.nodes),
    objects: new Map(
      [...objects].flatMap(([name, { paths }]) =>
        paths.map((path) => [path, name] as const),
      ),
    ),
  };
  const lines = [
    "// Generated by `bun run codegen` in apps/ios. Don't edit it.",
    "",
    ...serializedNode(schema.nodes),
    ...traitsTable(schema.traits),
    ...[...names.enums]
      .sort(([, a], [, b]) => byCodeUnits(a, b))
      .flatMap(([signature, name]) => enumeration(name, signature)),
    ...[...objects]
      .sort(([a], [b]) => byCodeUnits(a, b))
      .flatMap(([name, { type, paths }]) =>
        declaredObject(name, type, paths[0] ?? name, names),
      ),
    ...schema.nodes.flatMap((node) => payload(node, names)),
  ];
  return `${lines.join("\n").trimEnd()}\n`;
}

function serializedNode(nodes: NodeDescription[]): string[] {
  const cases = nodes.map((node) => ({
    name: identifier(
      className(node).charAt(0).toLowerCase() + className(node).slice(1),
    ),
    payload: payloadName(node),
    type: node.type,
  }));
  if (cases.some(({ name }) => name === "opaque")) {
    throw new Error("A node class can't be called OpaqueNode");
  }
  return [
    "public enum SerializedNode: Equatable, Sendable {",
    ...cases.map(({ name, payload }) => `  case ${name}(${payload})`),
    "  /// A node whose type isn't declared, kept exactly as read.",
    "  case opaque(JSONValue)",
    "",
    "  public init(json: JSONValue) {",
    '    switch json["type"]?.stringValue {',
    ...cases.map(
      ({ name, type }) =>
        `    case ${swiftString(type)}: self.init(json, as: Self.${name})`,
    ),
    "    default: self = .opaque(json)",
    "    }",
    "  }",
    "",
    "  public var payload: (any NodePayload)? {",
    "    switch self {",
    ...cases.map(({ name }) => `    case .${name}(let node): node`),
    "    case .opaque: nil",
    "    }",
    "  }",
    "",
    "  public var json: JSONValue {",
    "    switch self {",
    ...cases.map(({ name }) => `    case .${name}(let node): node.json`),
    "    case .opaque(let json): json",
    "    }",
    "  }",
    "",
    "  public func resolved() -> SerializedNode {",
    "    switch self {",
    ...cases.map(
      ({ name }) => `    case .${name}(let node): .${name}(node.resolved())`,
    ),
    "    case .opaque: self",
    "    }",
    "  }",
    "}",
    "",
  ];
}

function traitsTable(traits: Record<string, NodeTraits>): string[] {
  const kinds: Record<NodeTraits["kind"], string> = {
    element: ".element",
    text: ".text",
    linebreak: ".lineBreak",
    decorator: ".decorator",
  };
  const trait = (value: Trait): string =>
    typeof value === "boolean"
      ? `.fixed(${value})`
      : `.field(${swiftString(value.field)})`;
  return [
    "extension NodeTraits {",
    "  /// Every registered node's, declared or not, by type.",
    "  public static let byType: [String: NodeTraits] = [",
    ...Object.entries(traits)
      .sort(([a], [b]) => byCodeUnits(a, b))
      .map(
        ([type, { kind, inline, shadowRoot, canBeEmpty }]) =>
          `    ${swiftString(type)}: NodeTraits(kind: ${kinds[kind]}, inline: ${trait(inline)}, shadowRoot: ${trait(shadowRoot)}, canBeEmpty: ${trait(canBeEmpty)}),`,
      ),
    "  ]",
    "}",
    "",
  ];
}

function enumeration(name: string, signature: string): string[] {
  const cases = (JSON.parse(signature) as string[]).map((value) => {
    const member = caseName(value);
    return member === value
      ? `  case ${member}`
      : `  case ${member} = ${swiftString(value)}`;
  });
  return [
    `public enum ${name}: String, CaseIterable, Sendable, JSONEnumeration {`,
    ...cases,
    "}",
    "",
  ];
}

/** One property of a payload or object, read and written through its schema. */
type Member = {
  key: string;
  name: string;
  property: string;
  schemaType: string;
  schema: string;
  accessor: string;
  /** Node state, which isn't written where it is its default. */
  state: boolean;
  /** Node state kept under `$` rather than beside the fields. */
  nested: boolean;
};

type Place = "field" | "state" | "nested state";

function members(
  entries: [key: string, type: FieldType, place: Place][],
  reserved: Set<string>,
  names: Names,
  path: (key: string) => string,
): Member[] {
  return entries
    .sort(([a], [b]) => byCodeUnits(a, b))
    .map(([key, type, place]) => {
      if (reserved.has(key)) {
        throw new Error(`${path(key)}: a field can't be called ${key}`);
      }
      const field = swiftField(type, names, path(key));
      if (place !== "field" && field.nullable) {
        throw new Error(
          `${path(key)}: state can be null, which codegen doesn't type yet`,
        );
      }
      return {
        key,
        name: identifier(key),
        property: field.nullable
          ? `Nullable<${field.value}>`
          : `${field.value}?`,
        schemaType: field.nullable ? `${field.value}?` : field.value,
        schema: field.schema,
        accessor: field.nullable ? "Nullable" : "",
        state: place !== "field",
        nested: place === "nested state",
      };
    });
}

/** The body shared by payloads and objects: properties, reading, writing. */
function memberLines(
  fields: Member[],
  start: { read: string; write: string },
  extra: { read: string[]; write: string[] },
): {
  properties: string[];
  read: string[];
  write: string[];
  resolved: string[];
  schema: string[];
} {
  const state = fields.filter(({ nested }) => nested);
  const into = ({ nested }: Member) => (nested ? "state" : "fields");
  const binding = (line: string, changes: string[]) =>
    fields.length + changes.length > 0 ? line : line.replace("var ", "let ");
  return {
    properties: fields.map(
      ({ name, property }) => `  public var ${name}: ${property}`,
    ),
    read: [
      binding(start.read, extra.read),
      ...extra.read,
      ...(state.length > 0 ? ["    var state = fields.takeState()"] : []),
      ...fields.map(
        (member) =>
          `    ${member.name} = ${into(member)}.take${member.accessor}(${swiftString(member.key)}, Schema.${member.name})`,
      ),
      ...(state.length > 0 ? ["    fields.putState(state)"] : []),
      "    unknownFields = fields.rest",
    ],
    write: [
      binding(start.write, extra.write),
      ...extra.write,
      ...(state.length > 0 ? ["    var state = fields.takeState()"] : []),
      ...fields.map(
        (member) =>
          `    ${into(member)}.put${member.accessor}${member.state ? "UnlessDefault" : ""}(${swiftString(member.key)}, ${member.name}, Schema.${member.name})`,
      ),
      ...(state.length > 0 ? ["    fields.putState(state)"] : []),
      "    return fields.json",
    ],
    resolved:
      fields.length > 0
        ? [
            "    var node = self",
            ...fields.map(
              ({ name, state }) =>
                `    node.${name} = Schema.${name}.${state ? "omittingDefault" : "resolving"}(${name})`,
            ),
            "    return node",
          ]
        : ["    self"],
    schema:
      fields.length > 0
        ? [
            "",
            "  private enum Schema {",
            ...fields.map(
              ({ name, schemaType, schema }) =>
                `    static let ${name}: FieldSchema<${schemaType}> = ${schema}`,
            ),
            "  }",
          ]
        : [],
  };
}

function payload(node: NodeDescription, names: Names): string[] {
  const fields = members(
    [
      ...Object.entries(node.fields).map(
        ([key, type]) => [key, type, "field"] as [string, FieldType, Place],
      ),
      ...Object.entries(node.state).map(
        ([key, state]) =>
          [key, state.value, state.flat ? "state" : "nested state"] as [
            string,
            FieldType,
            Place,
          ],
      ),
    ],
    RESERVED_MEMBERS,
    names,
    (key) => `${node.type}.${key}`,
  );
  const lines = memberLines(
    fields,
    {
      read: "    var fields = try NodeFields(reading: json, as: Self.type)",
      write:
        "    var fields = NodeFields(writing: Self.type, over: unknownFields)",
    },
    node.children
      ? {
          read: ["    children = fields.takeChildren()"],
          write: ["    fields.putChildren(children)"],
        }
      : { read: [], write: [] },
  );
  return [
    `public struct ${payloadName(node)}: ${node.children ? "ParentNodePayload" : "NodePayload"} {`,
    `  public static let type = ${swiftString(node.type)}`,
    `  public static let version = ${node.version}`,
    ...(node.children ? ["  public var children: [SerializedNode]?"] : []),
    ...lines.properties,
    "  public var unknownFields: [String: JSONValue]",
    "",
    "  public init(json: JSONValue) throws {",
    ...lines.read,
    "  }",
    "",
    "  public var json: JSONValue {",
    ...lines.write,
    "  }",
    "",
    "  public func resolved() -> Self {",
    ...lines.resolved,
    "  }",
    ...lines.schema,
    "}",
    "",
  ];
}

function declaredObject(
  name: string,
  type: ObjectType,
  path: string,
  names: Names,
): string[] {
  const fields = members(
    Object.entries(type.fields).map(([key, field]) => [key, field, "field"]),
    RESERVED_OBJECT_MEMBERS,
    names,
    (key) => `${path}.${key}`,
  );
  const lines = memberLines(
    fields,
    {
      read: "    var fields = NodeFields(object)",
      write: "    var fields = NodeFields(over: unknownFields)",
    },
    { read: [], write: [] },
  );
  return [
    `public struct ${name}: DeclaredObject {`,
    ...lines.properties,
    "  public var unknownFields: [String: JSONValue]",
    "",
    `  static let isOpen = ${type.open === true}`,
    `  static let defaultValue = Self(${swiftJSON(defaultOf(type, path))})`,
    `  static let fieldFits: [String: @Sendable (JSONValue) -> Fit] = ${
      fields.length === 0
        ? "[:]"
        : `[${fields.map(({ key, name }) => `${swiftString(key)}: Schema.${name}.fit`).join(", ")}]`
    }`,
    "",
    "  init(_ object: [String: JSONValue]) {",
    ...lines.read,
    "  }",
    "",
    "  public var json: JSONValue {",
    ...lines.write,
    "  }",
    ...lines.schema,
    "}",
    "",
  ];
}

/**
 * A field's Swift value type, whether JSON `null` is among its values, and
 * the `FieldSchema` expression that reads it.
 */
function swiftField(
  type: FieldType,
  names: Names,
  where: string,
): { value: string; nullable: boolean; schema: string } {
  switch (type.kind) {
    case "string":
      return {
        value: "String",
        nullable: false,
        schema: `.string(default: ${literal(defaultOf(type, where), type, names, where)})`,
      };
    case "boolean":
      return {
        value: "Bool",
        nullable: false,
        schema: `.boolean(default: ${literal(defaultOf(type, where), type, names, where)})`,
      };
    case "number": {
      const options = [
        `default: ${literal(defaultOf(type, where), type, names, where)}`,
        ...(type.min === undefined ? [] : [`min: ${type.min}`]),
        ...(type.max === undefined ? [] : [`max: ${type.max}`]),
        ...(type.clamp ? ["clamp: true"] : []),
      ].join(", ");
      return type.integer
        ? { value: "Int", nullable: false, schema: `.integer(${options})` }
        : { value: "Double", nullable: false, schema: `.number(${options})` };
    }
    case "enum": {
      const name = enumName(type, names, where);
      const fallback =
        type.default === undefined
          ? "nil"
          : type.default === null
            ? `${name}?.none`
            : literal(type.default, type, names, where);
      return {
        value: name,
        nullable: type.values.includes(null),
        schema: `.enumeration(default: ${fallback})`,
      };
    }
    case "nullable": {
      const inner = swiftField(type.inner, names, where);
      if (inner.nullable) {
        throw new Error(`${where}: a nullable field can't hold null twice`);
      }
      return {
        value: inner.value,
        nullable: true,
        schema: `.nullable(${inner.schema}${type.defaultAsNull ? ", defaultAsNull: true" : ""})`,
      };
    }
    case "optional": {
      const inner = swiftField(type.inner, names, where);
      return {
        ...inner,
        schema: `.optional(${inner.schema}${type.omitDefault ? ", omitDefault: true" : ""})`,
      };
    }
    case "aliased": {
      const inner = swiftField(type.inner, names, where);
      const aliases = Object.entries(type.aliases)
        .sort(([a], [b]) => byCodeUnits(a, b))
        .map(
          ([alias, value]) =>
            `${swiftString(alias)}: ${literal(value, type.inner, names, where)}`,
        )
        .join(", ");
      return { ...inner, schema: `.aliased(${inner.schema}, [${aliases}])` };
    }
    case "array": {
      if (readsAsAbsent(type.item)) {
        throw new Error(`${where}: an array item can't read as absent`);
      }
      const item = swiftField(type.item, names, `${where}[]`);
      return {
        value: `[${item.value}${item.nullable ? "?" : ""}]`,
        nullable: false,
        schema: `.array(${item.schema})`,
      };
    }
    case "raw":
      return { value: "JSONValue", nullable: false, schema: ".raw" };
    case "object": {
      const name = names.objects.get(where);
      if (!name) throw new Error(`${where}: an object without a name`);
      return { value: name, nullable: false, schema: ".object" };
    }
    case "transform": {
      if (type.name === undefined) {
        throw new Error(
          `${where}: an unnamed transform; declare it with namedTransform`,
        );
      }
      const inner = swiftField(type.inner, names, where);
      return {
        ...inner,
        schema: `.transform(${inner.schema}, Transforms.${identifier(type.name)})`,
      };
    }
    default:
      throw new Error(`${where}: codegen doesn't type ${type.kind} fields yet`);
  }
}

/** The type a wrapping field type reads its value through. */
function innerType(type: FieldType): FieldType | undefined {
  switch (type.kind) {
    case "nullable":
    case "optional":
    case "aliased":
    case "transform":
      return type.inner;
    default:
      return undefined;
  }
}

function readsAsAbsent(type: FieldType): boolean {
  if (type.kind === "optional" || type.kind === "raw") return true;
  if (type.kind === "enum") return type.default === undefined;
  const inner = innerType(type);
  return inner !== undefined && readsAsAbsent(inner);
}

/** A JSON value as a Swift literal of `type`'s value type. */
function literal(
  value: unknown,
  type: FieldType,
  names: Names,
  where: string,
): string {
  switch (type.kind) {
    case "string":
      return swiftString(value as string);
    case "boolean":
    case "number":
      return String(value);
    case "enum":
      return value === null
        ? "nil"
        : `${enumName(type, names, where)}.${caseName(value as string)}`;
    case "nullable":
      return value === null ? "nil" : literal(value, type.inner, names, where);
    case "optional":
    case "aliased":
      return literal(value, type.inner, names, where);
    case "array":
      return `[${(value as unknown[]).map((item) => literal(item, type.item, names, `${where}[]`)).join(", ")}]`;
    default:
      throw new Error(`${where}: no Swift literal for a ${type.kind} value`);
  }
}

function defaultOf(type: FieldType, where: string) {
  if (type.default === undefined) throw new Error(`${where} has no default`);
  return type.default;
}

/**
 * Calls `visit` with every field type in `nodes`, down through wrappers,
 * arrays and objects, with its path and the name of the field it is under.
 */
function walk(
  nodes: NodeDescription[],
  visit: (type: FieldType, path: string, field: string) => void,
): void {
  const into = (type: FieldType, path: string, field: string): void => {
    visit(type, path, field);
    if (type.kind === "array") into(type.item, `${path}[]`, field);
    else if (type.kind === "object") {
      for (const [key, inner] of Object.entries(type.fields)) {
        into(inner, `${path}.${key}`, key);
      }
    } else {
      const inner = innerType(type);
      if (inner) into(inner, path, field);
    }
  };
  for (const node of nodes) {
    for (const [key, type] of Object.entries(node.fields)) {
      into(type, `${node.type}.${key}`, key);
    }
    for (const [key, state] of Object.entries(node.state)) {
      into(state.value, `${node.type}.${key}`, key);
    }
  }
}

/** Every enum's Swift name, by its signature. */
function enumNames(nodes: NodeDescription[]): Map<string, string> {
  const bySignature = new Map<string, Set<string>>();
  walk(nodes, (type, _path, field) => {
    if (type.kind !== "enum") return;
    const signature = enumSignature(type.values);
    if (signature === NOTHING_BUT_NULL) return;
    bySignature.set(
      signature,
      (bySignature.get(signature) ?? new Set()).add(field),
    );
  });
  const names = new Map<string, string>();
  for (const [signature, fields] of bySignature) {
    const named = ENUM_NAMES[signature];
    if (!named && fields.size > 1) {
      throw new Error(
        `The enum ${signature} is used by ${[...fields].join(", ")}; name it in ENUM_NAMES`,
      );
    }
    names.set(signature, named ?? pascalCase([...fields][0] ?? ""));
  }
  const taken = new Map<string, string>();
  for (const [signature, name] of names) {
    const other = taken.get(name);
    if (other !== undefined) {
      throw new Error(
        `The enums ${other} and ${signature} would both be ${name}; name them in ENUM_NAMES`,
      );
    }
    taken.set(name, signature);
  }
  return names;
}

/**
 * Every declared object's Swift struct, by name, with the paths it is at.
 * Objects at different paths share a struct when they take the same name,
 * which they may only do by being the same object.
 */
function objectTypes(
  nodes: NodeDescription[],
): Map<string, { type: ObjectType; paths: string[] }> {
  const objects = new Map<string, { type: ObjectType; paths: string[] }>();
  walk(nodes, (type, path, field) => {
    if (type.kind !== "object") return;
    const name = OBJECT_NAMES[path] ?? OBJECT_NAMES[field] ?? pascalCase(field);
    const named = objects.get(name);
    if (!named) {
      objects.set(name, { type, paths: [path] });
    } else if (JSON.stringify(named.type) === JSON.stringify(type)) {
      named.paths.push(path);
    } else {
      throw new Error(
        `The objects at ${named.paths[0]} and ${path} would both be ${name}; name them in OBJECT_NAMES`,
      );
    }
  });
  return objects;
}

function enumName(
  type: Extract<FieldType, { kind: "enum" }>,
  names: Names,
  where: string,
): string {
  const signature = enumSignature(type.values);
  if (signature === NOTHING_BUT_NULL) return "Never";
  const name = names.enums.get(signature);
  if (!name) throw new Error(`${where}: an enum without a name`);
  return name;
}

/**
 * The signature of an enum whose only value is null, a constant: a Swift enum
 * can't be empty, and `Never?` holds just that null.
 */
const NOTHING_BUT_NULL = "[]";

/** An enum's identity: its non-null values, in order. */
function enumSignature(values: unknown[]): string {
  const members = values.filter((value) => value !== null);
  if (members.some((value) => typeof value !== "string")) {
    throw new Error(
      `Codegen only types enums of strings, not ${JSON.stringify(values)}`,
    );
  }
  return JSON.stringify(members);
}

function caseName(value: string): string {
  return value === "" ? "empty" : identifier(camelCase(value));
}

/** The class name without its `Node` suffix, e.g. `ListItem`. */
function className(node: NodeDescription): string {
  return node.className.replace(/Node$/, "");
}

function payloadName(node: NodeDescription): string {
  return `Serialized${className(node)}Node`;
}

function pascalCase(name: string): string {
  const camel = camelCase(name);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function camelCase(name: string): string {
  return name.replace(/[^A-Za-z0-9]+(.)?/g, (_, next: string | undefined) =>
    (next ?? "").toUpperCase(),
  );
}

function identifier(name: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    throw new Error(`${JSON.stringify(name)} isn't a Swift identifier`);
  }
  return SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

/** A JSON value as a Swift `JSONValue` literal. */
function swiftJSON(value: unknown): string {
  if (value === null) return "nil";
  if (typeof value === "string") return swiftString(value);
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (Array.isArray(value)) return `[${value.map(swiftJSON).join(", ")}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, member]) => member !== undefined)
    .sort(([a], [b]) => byCodeUnits(a, b));
  return entries.length === 0
    ? "[:]"
    : `[${entries.map(([key, member]) => `${swiftString(key)}: ${swiftJSON(member)}`).join(", ")}]`;
}

function swiftString(value: string): string {
  let escaped = "";
  for (const char of value) {
    const code = char.codePointAt(0) ?? 0;
    escaped +=
      char === "\\" || char === '"'
        ? `\\${char}`
        : char === "\n"
          ? "\\n"
          : char === "\r"
            ? "\\r"
            : char === "\t"
              ? "\\t"
              : code < 0x20
                ? `\\u{${code.toString(16)}}`
                : char;
  }
  return `"${escaped}"`;
}
