/// <reference types="bun" />
/**
 * Rebuilds `src/server/drawings/fonts` from the pinned `@excalidraw/excalidraw`.
 *
 * PNG rendering rasterises the exported SVG with resvg, which reads fonts from
 * files and understands TrueType, not the WOFF2 the editor ships for the
 * browser. The files here are those same WOFF2 faces decompressed, so a label
 * rasterises with the font the editor drew it in. They are checked in because
 * the render path reads them from disk at request time: generating them during
 * the build would add a build step whose output still has to be traced into
 * the function.
 *
 * Run `bun run fonts:sync` after bumping `@excalidraw/excalidraw`, which is
 * pinned by the root `overrides`; the faces are content-hashed, so a bump that
 * changes a font shows up as added and removed files.
 *
 * Licensing, as the upstream font folders record it: Comic Shanns is MIT
 * (Shannon Miwa), Nunito and Lilita One come from Google Fonts under OFL 1.1,
 * Liberation Sans and Cascadia Code are OFL 1.1, and Virgil and Excalifont are
 * Excalidraw's own faces, redistributed here from the MIT-licensed package
 * this app already renders drawings with.
 *
 * Xiaolai, the CJK fallback, is deliberately left out: it is 200 faces and
 * 25 MB of subsets, which is not worth carrying into every deployment for a
 * drawing that has no CJK text in it. CJK labels render in the PNG's fallback
 * font instead.
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { decompress } from "wawoff2";

const SOURCE = join(
  import.meta.dir,
  "..",
  "..",
  "..",
  "packages",
  "excalidraw-converter",
  "node_modules",
  "@excalidraw",
  "excalidraw",
  "dist",
  "prod",
  "fonts",
);

const TARGET = join(
  import.meta.dir,
  "..",
  "src",
  "server",
  "drawings",
  "fonts",
);

const SKIPPED = new Set(["Xiaolai"]);

/**
 * Load order, which is also resvg's search order: it takes the first face
 * whose family matches, and for a character that face has no glyph for, the
 * first face in the whole set that does. The hand-drawn families come first so
 * that a character outside the chosen face's subset is answered by a face that
 * still looks like the drawing, rather than by whichever family sorted first.
 * A family missing from here is appended, so a new one is rendered rather than
 * silently dropped.
 */
const FAMILY_ORDER = [
  "Excalifont",
  "Virgil",
  "ComicShanns",
  "Nunito",
  "Liberation",
  "Cascadia",
  "Lilita",
  "Assistant",
];

/**
 * How much of the Latin alphabet the face carries, as the number of probes
 * its character map answers. `A` alone does not separate the subsets: every
 * Google subset of Nunito has it, and only the Latin one has `\u00e9`. Read out
 * of the font because the subsets are named by content hash upstream, so
 * nothing else says which is which. Only the two unicode subtable formats the
 * editor's fonts use are understood; a face in any other format scores zero,
 * which costs it the first place in its family and nothing else.
 */
const PROBES = [0x41, 0xe9];

const families = (await readdir(SOURCE, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && !SKIPPED.has(entry.name))
  .map((entry) => entry.name)
  .toSorted((a, b) => rank(a) - rank(b));

function rank(family: string): number {
  const index = FAMILY_ORDER.indexOf(family);
  return index === -1 ? FAMILY_ORDER.length : index;
}

await rm(TARGET, { recursive: true, force: true });
await mkdir(TARGET, { recursive: true });

const ordered: string[] = [];
let total = 0;
for (const family of families) {
  const faces: { name: string; latin: number }[] = [];
  for (const file of (await readdir(join(SOURCE, family))).toSorted()) {
    if (!file.endsWith(".woff2")) continue;
    const woff2 = await Bun.file(join(SOURCE, family, file)).bytes();
    const ttf = await decompress(woff2);
    const name = `${file.slice(0, -".woff2".length)}.ttf`;
    await writeFile(join(TARGET, name), ttf);
    faces.push({ name, latin: latinScore(ttf) });
    total += ttf.length;
  }
  // Each family is split into subsets by unicode range, and which one a
  // hashed name holds is not visible from the name. The one carrying the
  // Latin alphabet goes first, because that is the one resvg answers the
  // family with.
  const sorted = faces
    .toSorted((a, b) => b.latin - a.latin)
    .map((face) => face.name);
  console.log(`${family}: ${sorted.length} faces, first ${sorted[0]}`);
  ordered.push(...sorted);
}

await writeFile(
  join(TARGET, "..", "fonts.generated.ts"),
  `// Generated by scripts/sync-excalidraw-fonts.ts; do not edit.\n` +
    `export const EXCALIDRAW_FONT_FILES = [\n` +
    ordered.map((name) => `  ${JSON.stringify(name)},\n`).join("") +
    `] as const;\n`,
);

console.log(
  `${families.length} families, ${ordered.length} faces, ${(total / 1024 / 1024).toFixed(1)} MB`,
);

function latinScore(ttf: Uint8Array): number {
  const view = new DataView(ttf.buffer, ttf.byteOffset, ttf.byteLength);
  const tableCount = view.getUint16(4);
  let cmap: number | undefined;
  for (let index = 0; index < tableCount; index++) {
    const record = 12 + index * 16;
    const tag = String.fromCharCode(...ttf.subarray(record, record + 4));
    if (tag === "cmap") cmap = view.getUint32(record + 8);
  }
  if (cmap === undefined) return 0;

  const subtables = view.getUint16(cmap + 2);
  const found = new Set<number>();
  for (let index = 0; index < subtables; index++) {
    const record = cmap + 4 + index * 8;
    const platform = view.getUint16(record);
    const encoding = view.getUint16(record + 2);
    const unicode =
      platform === 0 || (platform === 3 && (encoding === 1 || encoding === 10));
    if (!unicode) continue;
    const table = cmap + view.getUint32(record + 4);
    for (const probe of PROBES) {
      if (covers(view, table, probe)) found.add(probe);
    }
  }
  return found.size;
}

function covers(view: DataView, offset: number, code: number): boolean {
  const format = view.getUint16(offset);
  if (format === 4) {
    const segments = view.getUint16(offset + 6) / 2;
    for (let segment = 0; segment < segments; segment++) {
      const end = view.getUint16(offset + 14 + segment * 2);
      const start = view.getUint16(offset + 16 + segments * 2 + segment * 2);
      if (start <= code && code <= end && end !== 0xffff) return true;
    }
    return false;
  }
  if (format === 12) {
    const groups = view.getUint32(offset + 12);
    for (let group = 0; group < groups; group++) {
      const at = offset + 16 + group * 12;
      if (view.getUint32(at) <= code && code <= view.getUint32(at + 4)) {
        return true;
      }
    }
  }
  return false;
}
