// Generated by `bun run codegen` in apps/ios. Don't edit it.

/// `EDITOR_NAMESPACE`: what a clipboard payload of nodes has to carry to
/// paste as nodes.
public let editorNamespace = #"Lexidraw"#

/// The link patterns in `packages/lexical-nodes/src/links.ts`.
enum LinkPatterns {
  static let autoLinkURL = #"/((https?:\/\/(www\.)?)|(www\.))[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)(?<![-.+():%])/"#
  static let autoLinkEmail = #"/(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))/"#
  static let linkURL = #"/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=+$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=+$,\w]+@)[A-Za-z0-9.-]+)((?:\/[+~%/.\w-_]*)?\??(?:[-+=&;%@.\w_]*)#?(?:[\w]*))?)/"#
}
