// Generated by `bun run codegen` in apps/ios. Don't edit it.

extension MarkdownTransformer {
  /// `createTransformers()` in @packages/lexical-nodes: the web editor's
  /// markdown transformers, in the order it runs them.
  static let web: [MarkdownTransformer] = [
    MarkdownTransformer(kind: .multilineElement, name: nil, regExp: JSRegExp("^>\\s?\\[!([A-Za-z][\\w-]*)\\]([+-]?)(?:\\s+(.*?))?\\s*$", flags: "")),
    MarkdownTransformer(kind: .multilineElement, name: nil, regExp: JSRegExp("^(:{3,})\\s*([A-Za-z][\\w-]*)(?:\\[(.*)\\])?(?:\\s+(.*?))?\\s*$", flags: "")),
    MarkdownTransformer(kind: .multilineElement, name: nil, regExp: JSRegExp("^\\s*<details(?:\\s[^>]*)?>", flags: "i")),
    MarkdownTransformer(kind: .multilineElement, name: nil, regExp: JSRegExp("^\\s*<columns(?:\\s[^>]*)?>\\s*$", flags: "i")),
    MarkdownTransformer(kind: .multilineElement, name: nil, regExp: JSRegExp("^\\s*\\$\\$\\s*$", flags: ""), isEndRequired: true),
    MarkdownTransformer(kind: .element, name: nil, regExp: JSRegExp("<tweet id=\"([^\"]+?)\"\\s?\\/>\\s?$", flags: "")),
    MarkdownTransformer(kind: .element, name: nil, regExp: JSRegExp("^<article\\s+.*?>$", flags: "")),
    MarkdownTransformer(kind: .element, name: nil, regExp: JSRegExp("^<!-- lexidraw:([a-z-]+)#(\\d+)(?: (.*?))? -->$", flags: "")),
    MarkdownTransformer(kind: .element, name: nil, regExp: JSRegExp("^\\$\\$(?!\\$)(.*?[^$])\\$\\$\\s*$", flags: "")),
    MarkdownTransformer(kind: .textMatch, name: nil, regExp: JSRegExp("!\\[([^[\\]]*)\\]\\(\\s*(<[^>]*>|[^\\s()]+)(?:\\s+(?:\"((?:[^\"\\\\]|\\\\.)*)\"|'([^']*)'))?\\s*\\)(?:\\{([^{}\\n]*)\\})?$", flags: ""), trigger: ")"),
    MarkdownTransformer(kind: .textMatch, name: nil, regExp: JSRegExp("(?<![\\\\$])\\$(?![\\s$])([^$\\n]*?[^\\s\\\\$])\\$(?![\\d$])$", flags: ""), trigger: "$"),
    MarkdownTransformer(kind: .textMatch, name: nil),
    MarkdownTransformer(kind: .textMatch, name: nil, regExp: JSRegExp("<!-- lexidraw:([a-z-]+)#(\\d+)(?: (.*?))? -->$", flags: "")),
    MarkdownTransformer(kind: .element, name: nil, regExp: JSRegExp("^\\[\\^([^\\]\\s]+)\\]:\\s+", flags: "")),
    MarkdownTransformer(kind: .textMatch, name: nil, regExp: JSRegExp("\\[\\^([^\\]\\s]+)\\]$", flags: "")),
    MarkdownTransformer(kind: .element, name: nil, regExp: JSRegExp("^(?:\\|)(.+)(?:\\|)\\s?$", flags: "")),
    MarkdownTransformer(kind: .element, name: .hr, regExp: JSRegExp("^(---|\\*\\*\\*|___)\\s?$", flags: "")),
    MarkdownTransformer(kind: .textMatch, name: .emoji, regExp: JSRegExp(":([a-z0-9_]+):$", flags: ""), trigger: ":"),
    MarkdownTransformer(kind: .element, name: .checkList, regExp: JSRegExp("^(\\s*)(?:[-*+]\\s)?\\s?(\\[(\\s|x)?\\])\\s", flags: "i"), triggerOnEnter: true),
    MarkdownTransformer(kind: .element, name: .heading, regExp: JSRegExp("^(#{1,6})\\s", flags: ""), triggerOnEnter: true),
    MarkdownTransformer(kind: .element, name: .quote, regExp: JSRegExp("^>\\s", flags: ""), triggerOnEnter: true),
    MarkdownTransformer(kind: .element, name: .unorderedList, regExp: JSRegExp("^(\\s*)[-*+]\\s", flags: ""), triggerOnEnter: true),
    MarkdownTransformer(kind: .element, name: .orderedList, regExp: JSRegExp("^(\\s*)(\\d{1,})\\.\\s", flags: ""), triggerOnEnter: true),
    MarkdownTransformer(kind: .multilineElement, name: .code, regExp: JSRegExp("^([ \\t]*`{3,})([\\w-]+)?[ \\t]?", flags: "")),
    MarkdownTransformer(kind: .textFormat, name: .inlineCode, tag: "`", formats: [.code]),
    MarkdownTransformer(kind: .textFormat, name: .boldItalicStar, tag: "***", formats: [.bold, .italic]),
    MarkdownTransformer(kind: .textFormat, name: .boldItalicUnderscore, tag: "___", formats: [.bold, .italic], isIntraword: false),
    MarkdownTransformer(kind: .textFormat, name: .boldStar, tag: "**", formats: [.bold]),
    MarkdownTransformer(kind: .textFormat, name: .boldUnderscore, tag: "__", formats: [.bold], isIntraword: false),
    MarkdownTransformer(kind: .textFormat, name: .highlight, tag: "==", formats: [.highlight]),
    MarkdownTransformer(kind: .textFormat, name: .italicStar, tag: "*", formats: [.italic]),
    MarkdownTransformer(kind: .textFormat, name: .italicUnderscore, tag: "_", formats: [.italic], isIntraword: false),
    MarkdownTransformer(kind: .textFormat, name: .strikethrough, tag: "~~", formats: [.strikethrough]),
    MarkdownTransformer(kind: .textMatch, name: .link, regExp: JSRegExp("(?:\\[([^[\\]]*(?:\\[[^[\\]]*\\][^[\\]]*)*)\\])(?:\\(\\s*(?:(?:<((?:\\\\.|[^<>\\n\\\\])*)>|((?!<)(?:\\\\[^\\s]|\\\\(?=\\s)|\\((?:\\\\[^\\s]|[^\\s()\\\\]|\\((?:\\\\[^\\s]|[^\\s()\\\\]|\\((?:\\\\[^\\s]|[^\\s()\\\\])*\\))*\\))*\\)|[^\\s()\\\\])+))(?:\\s+(?:\"((?:[^\"]*\\\\\")*[^\"]*)\"|'((?:[^']*\\\\')*[^']*)'|\\(((?:\\\\.|[^()\\\\])*)\\)))?\\s*)?\\))$", flags: ""), trigger: ")"),
  ]

  /// The name @lexical/markdown or the web editor exports a transformer by.
  enum Name: String, Sendable {
    case hr = "HR"
    case emoji = "EMOJI"
    case checkList = "CHECK_LIST"
    case heading = "HEADING"
    case quote = "QUOTE"
    case unorderedList = "UNORDERED_LIST"
    case orderedList = "ORDERED_LIST"
    case code = "CODE"
    case inlineCode = "INLINE_CODE"
    case boldItalicStar = "BOLD_ITALIC_STAR"
    case boldItalicUnderscore = "BOLD_ITALIC_UNDERSCORE"
    case boldStar = "BOLD_STAR"
    case boldUnderscore = "BOLD_UNDERSCORE"
    case highlight = "HIGHLIGHT"
    case italicStar = "ITALIC_STAR"
    case italicUnderscore = "ITALIC_UNDERSCORE"
    case strikethrough = "STRIKETHROUGH"
    case link = "LINK"
  }
}
