// Generated by `bun run codegen` in apps/ios. Don't edit it.

public enum SerializedNode: Equatable, Sendable {
  case autoLink(SerializedAutoLinkNode)
  case codeHighlight(SerializedCodeHighlightNode)
  case heading(SerializedHeadingNode)
  case horizontalRule(SerializedHorizontalRuleNode)
  case lineBreak(SerializedLineBreakNode)
  case link(SerializedLinkNode)
  case list(SerializedListNode)
  case listItem(SerializedListItemNode)
  case mark(SerializedMarkNode)
  case paragraph(SerializedParagraphNode)
  case quote(SerializedQuoteNode)
  case root(SerializedRootNode)
  case tab(SerializedTabNode)
  case table(SerializedTableNode)
  case tableCell(SerializedTableCellNode)
  case tableRow(SerializedTableRowNode)
  case text(SerializedTextNode)
  /// A node whose type isn't declared, kept exactly as read.
  case opaque(JSONValue)

  public init(json: JSONValue) {
    switch json["type"]?.stringValue {
    case "autolink": self.init(json, as: Self.autoLink)
    case "code-highlight": self.init(json, as: Self.codeHighlight)
    case "heading": self.init(json, as: Self.heading)
    case "horizontalrule": self.init(json, as: Self.horizontalRule)
    case "linebreak": self.init(json, as: Self.lineBreak)
    case "link": self.init(json, as: Self.link)
    case "list": self.init(json, as: Self.list)
    case "listitem": self.init(json, as: Self.listItem)
    case "mark": self.init(json, as: Self.mark)
    case "paragraph": self.init(json, as: Self.paragraph)
    case "quote": self.init(json, as: Self.quote)
    case "root": self.init(json, as: Self.root)
    case "tab": self.init(json, as: Self.tab)
    case "table": self.init(json, as: Self.table)
    case "tablecell": self.init(json, as: Self.tableCell)
    case "tablerow": self.init(json, as: Self.tableRow)
    case "text": self.init(json, as: Self.text)
    default: self = .opaque(json)
    }
  }

  public var payload: (any NodePayload)? {
    switch self {
    case .autoLink(let node): node
    case .codeHighlight(let node): node
    case .heading(let node): node
    case .horizontalRule(let node): node
    case .lineBreak(let node): node
    case .link(let node): node
    case .list(let node): node
    case .listItem(let node): node
    case .mark(let node): node
    case .paragraph(let node): node
    case .quote(let node): node
    case .root(let node): node
    case .tab(let node): node
    case .table(let node): node
    case .tableCell(let node): node
    case .tableRow(let node): node
    case .text(let node): node
    case .opaque: nil
    }
  }

  public var json: JSONValue {
    switch self {
    case .autoLink(let node): node.json
    case .codeHighlight(let node): node.json
    case .heading(let node): node.json
    case .horizontalRule(let node): node.json
    case .lineBreak(let node): node.json
    case .link(let node): node.json
    case .list(let node): node.json
    case .listItem(let node): node.json
    case .mark(let node): node.json
    case .paragraph(let node): node.json
    case .quote(let node): node.json
    case .root(let node): node.json
    case .tab(let node): node.json
    case .table(let node): node.json
    case .tableCell(let node): node.json
    case .tableRow(let node): node.json
    case .text(let node): node.json
    case .opaque(let json): json
    }
  }

  public func resolved() -> SerializedNode {
    switch self {
    case .autoLink(let node): .autoLink(node.resolved())
    case .codeHighlight(let node): .codeHighlight(node.resolved())
    case .heading(let node): .heading(node.resolved())
    case .horizontalRule(let node): .horizontalRule(node.resolved())
    case .lineBreak(let node): .lineBreak(node.resolved())
    case .link(let node): .link(node.resolved())
    case .list(let node): .list(node.resolved())
    case .listItem(let node): .listItem(node.resolved())
    case .mark(let node): .mark(node.resolved())
    case .paragraph(let node): .paragraph(node.resolved())
    case .quote(let node): .quote(node.resolved())
    case .root(let node): .root(node.resolved())
    case .tab(let node): .tab(node.resolved())
    case .table(let node): .table(node.resolved())
    case .tableCell(let node): .tableCell(node.resolved())
    case .tableRow(let node): .tableRow(node.resolved())
    case .text(let node): .text(node.resolved())
    case .opaque: self
    }
  }
}

extension NodeTraits {
  /// Every registered node's, declared or not, by type.
  public static let byType: [String: NodeTraits] = [
    "article": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "autocomplete": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "autolink": NodeTraits(kind: .element, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "callout": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "chart": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "code": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "code-highlight": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "collapsible-container": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "collapsible-content": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(true)),
    "collapsible-title": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "comment": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "equation": NodeTraits(kind: .decorator, inline: .field("inline"), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "excalidraw": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "figma": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "footnote-definition": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "footnote-reference": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "heading": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "horizontalrule": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "image": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "inline-image": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "layout-container": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "layout-item": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(true)),
    "linebreak": NodeTraits(kind: .lineBreak, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "link": NodeTraits(kind: .element, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "list": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "listitem": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "mark": NodeTraits(kind: .element, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "mermaid": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "page-break": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "paragraph": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "poll": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "quote": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .field("shadowRoot"), canBeEmpty: .fixed(true)),
    "root": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "slide-deck": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "sticky": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "tab": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "table": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "tablecell": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "tablerow": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "text": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "thread": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "tweet": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "video": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "youtube": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
  ]
}

public enum Direction: String, CaseIterable, Sendable, JSONEnumeration {
  case ltr
  case rtl
}

public enum ElementFormat: String, CaseIterable, Sendable, JSONEnumeration {
  case empty = ""
  case left
  case start
  case center
  case right
  case end
  case justify
}

public enum HeadingTag: String, CaseIterable, Sendable, JSONEnumeration {
  case h1
  case h2
  case h3
  case h4
  case h5
  case h6
}

public enum ListTag: String, CaseIterable, Sendable, JSONEnumeration {
  case ul
  case ol
}

public enum ListType: String, CaseIterable, Sendable, JSONEnumeration {
  case number
  case bullet
  case check
}

public enum TabMode: String, CaseIterable, Sendable, JSONEnumeration {
  case normal
}

public enum TextMode: String, CaseIterable, Sendable, JSONEnumeration {
  case normal
  case token
  case segmented
}

public enum VerticalAlign: String, CaseIterable, Sendable, JSONEnumeration {
  case middle
  case bottom
}

public struct SerializedAutoLinkNode: ElementNodePayload {
  public static let type = "autolink"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var isUnlinked: Bool?
  public var rel: Nullable<String>
  public var target: Nullable<String>
  public var textFormat: Double?
  public var textStyle: String?
  public var title: Nullable<String>
  public var url: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    isUnlinked = fields.take("isUnlinked", Schema.isUnlinked)
    rel = fields.takeNullable("rel", Schema.rel)
    target = fields.takeNullable("target", Schema.target)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    title = fields.takeNullable("title", Schema.title)
    url = fields.take("url", Schema.url)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("isUnlinked", isUnlinked, Schema.isUnlinked)
    fields.putNullable("rel", rel, Schema.rel)
    fields.putNullable("target", target, Schema.target)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.putNullable("title", title, Schema.title)
    fields.put("url", url, Schema.url)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.isUnlinked = Schema.isUnlinked.resolving(isUnlinked)
    node.rel = Schema.rel.resolving(rel)
    node.target = Schema.target.resolving(target)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.title = Schema.title.resolving(title)
    node.url = Schema.url.resolving(url)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let isUnlinked: FieldSchema<Bool> = .boolean(default: false)
    static let rel: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let target: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let title: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let url: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedCodeHighlightNode: NodePayload {
  public static let type = "code-highlight"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var highlightType: Nullable<String>
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    highlightType = fields.takeNullable("highlightType", Schema.highlightType)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.putNullable("highlightType", highlightType, Schema.highlightType)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.highlightType = Schema.highlightType.resolving(highlightType)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let highlightType: FieldSchema<String?> = .optional(.nullable(.string(default: "")))
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedHeadingNode: ElementNodePayload {
  public static let type = "heading"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var tag: HeadingTag?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    tag = fields.take("tag", Schema.tag)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("tag", tag, Schema.tag)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.tag = Schema.tag.resolving(tag)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let tag: FieldSchema<HeadingTag> = .enumeration(default: HeadingTag.h1)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedHorizontalRuleNode: NodePayload {
  public static let type = "horizontalrule"
  public static let version = 1
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    return fields.json
  }

  public func resolved() -> Self {
    self
  }
}

public struct SerializedLineBreakNode: NodePayload {
  public static let type = "linebreak"
  public static let version = 1
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    return fields.json
  }

  public func resolved() -> Self {
    self
  }
}

public struct SerializedLinkNode: ElementNodePayload {
  public static let type = "link"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var rel: Nullable<String>
  public var target: Nullable<String>
  public var textFormat: Double?
  public var textStyle: String?
  public var title: Nullable<String>
  public var url: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    rel = fields.takeNullable("rel", Schema.rel)
    target = fields.takeNullable("target", Schema.target)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    title = fields.takeNullable("title", Schema.title)
    url = fields.take("url", Schema.url)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.putNullable("rel", rel, Schema.rel)
    fields.putNullable("target", target, Schema.target)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.putNullable("title", title, Schema.title)
    fields.put("url", url, Schema.url)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.rel = Schema.rel.resolving(rel)
    node.target = Schema.target.resolving(target)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.title = Schema.title.resolving(title)
    node.url = Schema.url.resolving(url)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let rel: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let target: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let title: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let url: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedListNode: ElementNodePayload {
  public static let type = "list"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var listType: ListType?
  public var start: Double?
  public var tag: ListTag?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    listType = fields.take("listType", Schema.listType)
    start = fields.take("start", Schema.start)
    tag = fields.take("tag", Schema.tag)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("listType", listType, Schema.listType)
    fields.put("start", start, Schema.start)
    fields.put("tag", tag, Schema.tag)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.listType = Schema.listType.resolving(listType)
    node.start = Schema.start.resolving(start)
    node.tag = Schema.tag.resolving(tag)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let listType: FieldSchema<ListType> = .aliased(.enumeration(default: ListType.number), ["ol": ListType.number, "ul": ListType.bullet])
    static let start: FieldSchema<Double> = .number(default: 1)
    static let tag: FieldSchema<ListTag> = .enumeration(default: ListTag.ul)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedListItemNode: ElementNodePayload {
  public static let type = "listitem"
  public static let version = 1
  public var children: [SerializedNode]?
  public var checked: Bool?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var value: Double?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    checked = fields.take("checked", Schema.checked)
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    value = fields.take("value", Schema.value)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.put("checked", checked, Schema.checked)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.put("value", value, Schema.value)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.checked = Schema.checked.resolving(checked)
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.value = Schema.value.resolving(value)
    return node
  }

  private enum Schema {
    static let checked: FieldSchema<Bool> = .optional(.boolean(default: false))
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0, max: 128, clamp: true)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let value: FieldSchema<Double> = .number(default: 1)
  }
}

public struct SerializedMarkNode: ElementNodePayload {
  public static let type = "mark"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var ids: [String]?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    ids = fields.take("ids", Schema.ids)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("ids", ids, Schema.ids)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.ids = Schema.ids.resolving(ids)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let ids: FieldSchema<[String]> = .array(.string(default: ""))
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedParagraphNode: ElementNodePayload {
  public static let type = "paragraph"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .number(default: 0)
    static let textStyle: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedQuoteNode: ElementNodePayload {
  public static let type = "quote"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var shadowRoot: Bool?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    shadowRoot = fields.take("shadowRoot", Schema.shadowRoot)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("shadowRoot", shadowRoot, Schema.shadowRoot)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.shadowRoot = Schema.shadowRoot.omittingDefault(shadowRoot)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let shadowRoot: FieldSchema<Bool> = .boolean(default: false)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedRootNode: ElementNodePayload {
  public static let type = "root"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedTabNode: NodePayload {
  public static let type = "tab"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var mode: TabMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .number(default: 2)
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mode: FieldSchema<TabMode> = .enumeration(default: TabMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "\t")
  }
}

public struct SerializedTableNode: ElementNodePayload {
  public static let type = "table"
  public static let version = 1
  public var children: [SerializedNode]?
  public var colWidths: [Double]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var frozenColumnCount: Double?
  public var frozenRowCount: Double?
  public var indent: Int?
  public var rowStriping: Bool?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    colWidths = fields.take("colWidths", Schema.colWidths)
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    frozenColumnCount = fields.take("frozenColumnCount", Schema.frozenColumnCount)
    frozenRowCount = fields.take("frozenRowCount", Schema.frozenRowCount)
    indent = fields.take("indent", Schema.indent)
    rowStriping = fields.take("rowStriping", Schema.rowStriping)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.put("colWidths", colWidths, Schema.colWidths)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("frozenColumnCount", frozenColumnCount, Schema.frozenColumnCount)
    fields.put("frozenRowCount", frozenRowCount, Schema.frozenRowCount)
    fields.put("indent", indent, Schema.indent)
    fields.put("rowStriping", rowStriping, Schema.rowStriping)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.colWidths = Schema.colWidths.resolving(colWidths)
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.frozenColumnCount = Schema.frozenColumnCount.resolving(frozenColumnCount)
    node.frozenRowCount = Schema.frozenRowCount.resolving(frozenRowCount)
    node.indent = Schema.indent.resolving(indent)
    node.rowStriping = Schema.rowStriping.resolving(rowStriping)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let colWidths: FieldSchema<[Double]> = .optional(.array(.number(default: 0)))
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let frozenColumnCount: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let frozenRowCount: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let rowStriping: FieldSchema<Bool> = .optional(.boolean(default: false), omitDefault: true)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedTableCellNode: ElementNodePayload {
  public static let type = "tablecell"
  public static let version = 1
  public var children: [SerializedNode]?
  public var backgroundColor: Nullable<String>
  public var colSpan: Int?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var headerState: Double?
  public var indent: Int?
  public var rowSpan: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var verticalAlign: VerticalAlign?
  public var width: Double?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    backgroundColor = fields.takeNullable("backgroundColor", Schema.backgroundColor)
    colSpan = fields.take("colSpan", Schema.colSpan)
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    headerState = fields.take("headerState", Schema.headerState)
    indent = fields.take("indent", Schema.indent)
    rowSpan = fields.take("rowSpan", Schema.rowSpan)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    verticalAlign = fields.take("verticalAlign", Schema.verticalAlign)
    width = fields.take("width", Schema.width)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("backgroundColor", backgroundColor, Schema.backgroundColor)
    fields.put("colSpan", colSpan, Schema.colSpan)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("headerState", headerState, Schema.headerState)
    fields.put("indent", indent, Schema.indent)
    fields.put("rowSpan", rowSpan, Schema.rowSpan)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.put("verticalAlign", verticalAlign, Schema.verticalAlign)
    fields.put("width", width, Schema.width)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.backgroundColor = Schema.backgroundColor.resolving(backgroundColor)
    node.colSpan = Schema.colSpan.resolving(colSpan)
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.headerState = Schema.headerState.resolving(headerState)
    node.indent = Schema.indent.resolving(indent)
    node.rowSpan = Schema.rowSpan.resolving(rowSpan)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.verticalAlign = Schema.verticalAlign.resolving(verticalAlign)
    node.width = Schema.width.resolving(width)
    return node
  }

  private enum Schema {
    static let backgroundColor: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let colSpan: FieldSchema<Int> = .integer(default: 1, min: 1)
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let headerState: FieldSchema<Double> = .number(default: 0)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let rowSpan: FieldSchema<Int> = .integer(default: 1, min: 1)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let verticalAlign: FieldSchema<VerticalAlign> = .enumeration(default: nil)
    static let width: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
  }
}

public struct SerializedTableRowNode: ElementNodePayload {
  public static let type = "tablerow"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var height: Double?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    height = fields.take("height", Schema.height)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("height", height, Schema.height)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.height = Schema.height.resolving(height)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let height: FieldSchema<Double> = .optional(.number(default: 0))
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedTextNode: NodePayload {
  public static let type = "text"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
  }
}
