// Generated by `bun run codegen` in apps/ios. Don't edit it.

public enum SerializedNode: Equatable, Sendable {
  case autocomplete(SerializedAutocompleteNode)
  case autoLink(SerializedAutoLinkNode)
  case callout(SerializedCalloutNode)
  case codeHighlight(SerializedCodeHighlightNode)
  case collapsibleContainer(SerializedCollapsibleContainerNode)
  case collapsibleContent(SerializedCollapsibleContentNode)
  case collapsibleTitle(SerializedCollapsibleTitleNode)
  case comment(SerializedCommentNode)
  case emoji(SerializedEmojiNode)
  case footnoteDefinition(SerializedFootnoteDefinitionNode)
  case footnoteReference(SerializedFootnoteReferenceNode)
  case hashtag(SerializedHashtagNode)
  case heading(SerializedHeadingNode)
  case horizontalRule(SerializedHorizontalRuleNode)
  case keyword(SerializedKeywordNode)
  case layoutContainer(SerializedLayoutContainerNode)
  case layoutItem(SerializedLayoutItemNode)
  case lineBreak(SerializedLineBreakNode)
  case link(SerializedLinkNode)
  case list(SerializedListNode)
  case listItem(SerializedListItemNode)
  case mark(SerializedMarkNode)
  case mention(SerializedMentionNode)
  case pageBreak(SerializedPageBreakNode)
  case paragraph(SerializedParagraphNode)
  case poll(SerializedPollNode)
  case quote(SerializedQuoteNode)
  case root(SerializedRootNode)
  case sticky(SerializedStickyNode)
  case tab(SerializedTabNode)
  case table(SerializedTableNode)
  case tableCell(SerializedTableCellNode)
  case tableRow(SerializedTableRowNode)
  case text(SerializedTextNode)
  case thread(SerializedThreadNode)
  /// A node whose type isn't declared, kept exactly as read.
  case opaque(JSONValue)

  public init(json: JSONValue) {
    switch json["type"]?.stringValue {
    case "autocomplete": self.init(json, as: Self.autocomplete)
    case "autolink": self.init(json, as: Self.autoLink)
    case "callout": self.init(json, as: Self.callout)
    case "code-highlight": self.init(json, as: Self.codeHighlight)
    case "collapsible-container": self.init(json, as: Self.collapsibleContainer)
    case "collapsible-content": self.init(json, as: Self.collapsibleContent)
    case "collapsible-title": self.init(json, as: Self.collapsibleTitle)
    case "comment": self.init(json, as: Self.comment)
    case "emoji": self.init(json, as: Self.emoji)
    case "footnote-definition": self.init(json, as: Self.footnoteDefinition)
    case "footnote-reference": self.init(json, as: Self.footnoteReference)
    case "hashtag": self.init(json, as: Self.hashtag)
    case "heading": self.init(json, as: Self.heading)
    case "horizontalrule": self.init(json, as: Self.horizontalRule)
    case "keyword": self.init(json, as: Self.keyword)
    case "layout-container": self.init(json, as: Self.layoutContainer)
    case "layout-item": self.init(json, as: Self.layoutItem)
    case "linebreak": self.init(json, as: Self.lineBreak)
    case "link": self.init(json, as: Self.link)
    case "list": self.init(json, as: Self.list)
    case "listitem": self.init(json, as: Self.listItem)
    case "mark": self.init(json, as: Self.mark)
    case "mention": self.init(json, as: Self.mention)
    case "page-break": self.init(json, as: Self.pageBreak)
    case "paragraph": self.init(json, as: Self.paragraph)
    case "poll": self.init(json, as: Self.poll)
    case "quote": self.init(json, as: Self.quote)
    case "root": self.init(json, as: Self.root)
    case "sticky": self.init(json, as: Self.sticky)
    case "tab": self.init(json, as: Self.tab)
    case "table": self.init(json, as: Self.table)
    case "tablecell": self.init(json, as: Self.tableCell)
    case "tablerow": self.init(json, as: Self.tableRow)
    case "text": self.init(json, as: Self.text)
    case "thread": self.init(json, as: Self.thread)
    default: self = .opaque(json)
    }
  }

  public var payload: (any NodePayload)? {
    switch self {
    case .autocomplete(let node): node
    case .autoLink(let node): node
    case .callout(let node): node
    case .codeHighlight(let node): node
    case .collapsibleContainer(let node): node
    case .collapsibleContent(let node): node
    case .collapsibleTitle(let node): node
    case .comment(let node): node
    case .emoji(let node): node
    case .footnoteDefinition(let node): node
    case .footnoteReference(let node): node
    case .hashtag(let node): node
    case .heading(let node): node
    case .horizontalRule(let node): node
    case .keyword(let node): node
    case .layoutContainer(let node): node
    case .layoutItem(let node): node
    case .lineBreak(let node): node
    case .link(let node): node
    case .list(let node): node
    case .listItem(let node): node
    case .mark(let node): node
    case .mention(let node): node
    case .pageBreak(let node): node
    case .paragraph(let node): node
    case .poll(let node): node
    case .quote(let node): node
    case .root(let node): node
    case .sticky(let node): node
    case .tab(let node): node
    case .table(let node): node
    case .tableCell(let node): node
    case .tableRow(let node): node
    case .text(let node): node
    case .thread(let node): node
    case .opaque: nil
    }
  }

  public var json: JSONValue {
    switch self {
    case .autocomplete(let node): node.json
    case .autoLink(let node): node.json
    case .callout(let node): node.json
    case .codeHighlight(let node): node.json
    case .collapsibleContainer(let node): node.json
    case .collapsibleContent(let node): node.json
    case .collapsibleTitle(let node): node.json
    case .comment(let node): node.json
    case .emoji(let node): node.json
    case .footnoteDefinition(let node): node.json
    case .footnoteReference(let node): node.json
    case .hashtag(let node): node.json
    case .heading(let node): node.json
    case .horizontalRule(let node): node.json
    case .keyword(let node): node.json
    case .layoutContainer(let node): node.json
    case .layoutItem(let node): node.json
    case .lineBreak(let node): node.json
    case .link(let node): node.json
    case .list(let node): node.json
    case .listItem(let node): node.json
    case .mark(let node): node.json
    case .mention(let node): node.json
    case .pageBreak(let node): node.json
    case .paragraph(let node): node.json
    case .poll(let node): node.json
    case .quote(let node): node.json
    case .root(let node): node.json
    case .sticky(let node): node.json
    case .tab(let node): node.json
    case .table(let node): node.json
    case .tableCell(let node): node.json
    case .tableRow(let node): node.json
    case .text(let node): node.json
    case .thread(let node): node.json
    case .opaque(let json): json
    }
  }

  public func resolved() -> SerializedNode {
    switch self {
    case .autocomplete(let node): .autocomplete(node.resolved())
    case .autoLink(let node): .autoLink(node.resolved())
    case .callout(let node): .callout(node.resolved())
    case .codeHighlight(let node): .codeHighlight(node.resolved())
    case .collapsibleContainer(let node): .collapsibleContainer(node.resolved())
    case .collapsibleContent(let node): .collapsibleContent(node.resolved())
    case .collapsibleTitle(let node): .collapsibleTitle(node.resolved())
    case .comment(let node): .comment(node.resolved())
    case .emoji(let node): .emoji(node.resolved())
    case .footnoteDefinition(let node): .footnoteDefinition(node.resolved())
    case .footnoteReference(let node): .footnoteReference(node.resolved())
    case .hashtag(let node): .hashtag(node.resolved())
    case .heading(let node): .heading(node.resolved())
    case .horizontalRule(let node): .horizontalRule(node.resolved())
    case .keyword(let node): .keyword(node.resolved())
    case .layoutContainer(let node): .layoutContainer(node.resolved())
    case .layoutItem(let node): .layoutItem(node.resolved())
    case .lineBreak(let node): .lineBreak(node.resolved())
    case .link(let node): .link(node.resolved())
    case .list(let node): .list(node.resolved())
    case .listItem(let node): .listItem(node.resolved())
    case .mark(let node): .mark(node.resolved())
    case .mention(let node): .mention(node.resolved())
    case .pageBreak(let node): .pageBreak(node.resolved())
    case .paragraph(let node): .paragraph(node.resolved())
    case .poll(let node): .poll(node.resolved())
    case .quote(let node): .quote(node.resolved())
    case .root(let node): .root(node.resolved())
    case .sticky(let node): .sticky(node.resolved())
    case .tab(let node): .tab(node.resolved())
    case .table(let node): .table(node.resolved())
    case .tableCell(let node): .tableCell(node.resolved())
    case .tableRow(let node): .tableRow(node.resolved())
    case .text(let node): .text(node.resolved())
    case .thread(let node): .thread(node.resolved())
    case .opaque: self
    }
  }
}

extension NodeTraits {
  /// Every registered node's, declared or not, by type.
  public static let byType: [String: NodeTraits] = [
    "article": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "autocomplete": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "autolink": NodeTraits(kind: .element, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "callout": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "chart": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "code": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "code-highlight": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "collapsible-container": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "collapsible-content": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(true)),
    "collapsible-title": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "comment": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "emoji": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "equation": NodeTraits(kind: .decorator, inline: .field("inline"), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "excalidraw": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "figma": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "footnote-definition": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "footnote-reference": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "hashtag": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "heading": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "horizontalrule": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "image": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "inline-image": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "keyword": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "layout-container": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "layout-item": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(true)),
    "linebreak": NodeTraits(kind: .lineBreak, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "link": NodeTraits(kind: .element, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "list": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "listitem": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "mark": NodeTraits(kind: .element, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "mention": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "mermaid": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "page-break": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "paragraph": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "poll": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "quote": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .field("shadowRoot"), canBeEmpty: .fixed(true)),
    "root": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(true)),
    "slide-deck": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "sticky": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "tab": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "table": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "tablecell": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "tablerow": NodeTraits(kind: .element, inline: .fixed(false), shadowRoot: .fixed(true), canBeEmpty: .fixed(false)),
    "text": NodeTraits(kind: .text, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "thread": NodeTraits(kind: .decorator, inline: .fixed(true), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "tweet": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "video": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
    "youtube": NodeTraits(kind: .decorator, inline: .fixed(false), shadowRoot: .fixed(false), canBeEmpty: .fixed(false)),
  ]
}

public enum CalloutKind: String, CaseIterable, Sendable, JSONEnumeration {
  case note
  case tip
  case important
  case warning
  case caution
}

public enum CommentType: String, CaseIterable, Sendable, JSONEnumeration {
  case comment
}

public enum Direction: String, CaseIterable, Sendable, JSONEnumeration {
  case ltr
  case rtl
}

public enum ElementFormat: String, CaseIterable, Sendable, JSONEnumeration {
  case empty = ""
  case left
  case start
  case center
  case right
  case end
  case justify
}

public enum HeadingTag: String, CaseIterable, Sendable, JSONEnumeration {
  case h1
  case h2
  case h3
  case h4
  case h5
  case h6
}

public enum ListTag: String, CaseIterable, Sendable, JSONEnumeration {
  case ul
  case ol
}

public enum ListType: String, CaseIterable, Sendable, JSONEnumeration {
  case number
  case bullet
  case check
}

public enum StickyNoteColor: String, CaseIterable, Sendable, JSONEnumeration {
  case pink
  case yellow
  case green
  case blue
  case red
  case orange
  case purple
  case gray
}

public enum TabMode: String, CaseIterable, Sendable, JSONEnumeration {
  case normal
}

public enum TextMode: String, CaseIterable, Sendable, JSONEnumeration {
  case normal
  case token
  case segmented
}

public enum ThreadType: String, CaseIterable, Sendable, JSONEnumeration {
  case thread
}

public enum VerticalAlign: String, CaseIterable, Sendable, JSONEnumeration {
  case middle
  case bottom
}

public struct Comment: DeclaredObject {
  public var author: String?
  public var content: String?
  public var deleted: Bool?
  public var id: String?
  public var timeStamp: Double?
  public var type: CommentType?
  public var unknownFields: [String: JSONValue]

  static let isOpen = true
  static let defaultValue = Self(["author": "", "content": "", "deleted": false, "id": "", "timeStamp": 0, "type": "comment"])
  static let fieldFits: [String: @Sendable (JSONValue) -> Fit] = ["author": Schema.author.fit, "content": Schema.content.fit, "deleted": Schema.deleted.fit, "id": Schema.id.fit, "timeStamp": Schema.timeStamp.fit, "type": Schema.type.fit]

  init(_ object: [String: JSONValue]) {
    var fields = NodeFields(object)
    author = fields.take("author", Schema.author)
    content = fields.take("content", Schema.content)
    deleted = fields.take("deleted", Schema.deleted)
    id = fields.take("id", Schema.id)
    timeStamp = fields.take("timeStamp", Schema.timeStamp)
    type = fields.take("type", Schema.type)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(over: unknownFields)
    fields.put("author", author, Schema.author)
    fields.put("content", content, Schema.content)
    fields.put("deleted", deleted, Schema.deleted)
    fields.put("id", id, Schema.id)
    fields.put("timeStamp", timeStamp, Schema.timeStamp)
    fields.put("type", type, Schema.type)
    return fields.json
  }

  private enum Schema {
    static let author: FieldSchema<String> = .string(default: "")
    static let content: FieldSchema<String> = .string(default: "")
    static let deleted: FieldSchema<Bool> = .boolean(default: false)
    static let id: FieldSchema<String> = .string(default: "")
    static let timeStamp: FieldSchema<Double> = .number(default: 0)
    static let type: FieldSchema<CommentType> = .enumeration(default: CommentType.comment)
  }
}

public struct CommentThread: DeclaredObject {
  public var comments: [Comment]?
  public var id: String?
  public var quote: String?
  public var resolved: Bool?
  public var type: ThreadType?
  public var unknownFields: [String: JSONValue]

  static let isOpen = true
  static let defaultValue = Self(["comments": [], "id": "", "quote": "", "type": "thread"])
  static let fieldFits: [String: @Sendable (JSONValue) -> Fit] = ["comments": Schema.comments.fit, "id": Schema.id.fit, "quote": Schema.quote.fit, "resolved": Schema.resolved.fit, "type": Schema.type.fit]

  init(_ object: [String: JSONValue]) {
    var fields = NodeFields(object)
    comments = fields.take("comments", Schema.comments)
    id = fields.take("id", Schema.id)
    quote = fields.take("quote", Schema.quote)
    resolved = fields.take("resolved", Schema.resolved)
    type = fields.take("type", Schema.type)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(over: unknownFields)
    fields.put("comments", comments, Schema.comments)
    fields.put("id", id, Schema.id)
    fields.put("quote", quote, Schema.quote)
    fields.put("resolved", resolved, Schema.resolved)
    fields.put("type", type, Schema.type)
    return fields.json
  }

  private enum Schema {
    static let comments: FieldSchema<[Comment]> = .array(.object)
    static let id: FieldSchema<String> = .string(default: "")
    static let quote: FieldSchema<String> = .string(default: "")
    static let resolved: FieldSchema<Bool> = .optional(.boolean(default: false))
    static let type: FieldSchema<ThreadType> = .enumeration(default: ThreadType.thread)
  }
}

public struct Figure: DeclaredObject {
  public var caption: String?
  public var width: String?
  public var unknownFields: [String: JSONValue]

  static let isOpen = false
  static let defaultValue = Self([:])
  static let fieldFits: [String: @Sendable (JSONValue) -> Fit] = ["caption": Schema.caption.fit, "width": Schema.width.fit]

  init(_ object: [String: JSONValue]) {
    var fields = NodeFields(object)
    caption = fields.take("caption", Schema.caption)
    width = fields.take("width", Schema.width)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(over: unknownFields)
    fields.put("caption", caption, Schema.caption)
    fields.put("width", width, Schema.width)
    return fields.json
  }

  private enum Schema {
    static let caption: FieldSchema<String> = .optional(.string(default: ""))
    static let width: FieldSchema<String> = .optional(.transform(.string(default: ""), Transforms.figureWidth))
  }
}

public struct NestedEditor: DeclaredObject {
  public var editorState: JSONValue?
  public var unknownFields: [String: JSONValue]

  static let isOpen = false
  static let defaultValue = Self(["editorState": ["root": ["children": [], "direction": nil, "format": "", "indent": 0, "type": "root", "version": 1]]])
  static let fieldFits: [String: @Sendable (JSONValue) -> Fit] = ["editorState": Schema.editorState.fit]

  init(_ object: [String: JSONValue]) {
    var fields = NodeFields(object)
    editorState = fields.take("editorState", Schema.editorState)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(over: unknownFields)
    fields.put("editorState", editorState, Schema.editorState)
    return fields.json
  }

  private enum Schema {
    static let editorState: FieldSchema<JSONValue> = .raw
  }
}

public struct PollOption: DeclaredObject {
  public var text: String?
  public var uid: String?
  public var votes: [String]?
  public var unknownFields: [String: JSONValue]

  static let isOpen = true
  static let defaultValue = Self(["text": "", "uid": "", "votes": []])
  static let fieldFits: [String: @Sendable (JSONValue) -> Fit] = ["text": Schema.text.fit, "uid": Schema.uid.fit, "votes": Schema.votes.fit]

  init(_ object: [String: JSONValue]) {
    var fields = NodeFields(object)
    text = fields.take("text", Schema.text)
    uid = fields.take("uid", Schema.uid)
    votes = fields.take("votes", Schema.votes)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(over: unknownFields)
    fields.put("text", text, Schema.text)
    fields.put("uid", uid, Schema.uid)
    fields.put("votes", votes, Schema.votes)
    return fields.json
  }

  private enum Schema {
    static let text: FieldSchema<String> = .string(default: "")
    static let uid: FieldSchema<String> = .string(default: "")
    static let votes: FieldSchema<[String]> = .array(.string(default: ""))
  }
}

public struct SerializedAutocompleteNode: NodePayload {
  public static let type = "autocomplete"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var uuid: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    uuid = fields.take("uuid", Schema.uuid)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    fields.put("uuid", uuid, Schema.uuid)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    node.uuid = Schema.uuid.resolving(uuid)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
    static let uuid: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedAutoLinkNode: ParentNodePayload {
  public static let type = "autolink"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var isUnlinked: Bool?
  public var rel: Nullable<String>
  public var target: Nullable<String>
  public var textFormat: Double?
  public var textStyle: String?
  public var title: Nullable<String>
  public var url: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    isUnlinked = fields.take("isUnlinked", Schema.isUnlinked)
    rel = fields.takeNullable("rel", Schema.rel)
    target = fields.takeNullable("target", Schema.target)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    title = fields.takeNullable("title", Schema.title)
    url = fields.take("url", Schema.url)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("isUnlinked", isUnlinked, Schema.isUnlinked)
    fields.putNullable("rel", rel, Schema.rel)
    fields.putNullable("target", target, Schema.target)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.putNullable("title", title, Schema.title)
    fields.put("url", url, Schema.url)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.isUnlinked = Schema.isUnlinked.resolving(isUnlinked)
    node.rel = Schema.rel.resolving(rel)
    node.target = Schema.target.resolving(target)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.title = Schema.title.resolving(title)
    node.url = Schema.url.resolving(url)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let isUnlinked: FieldSchema<Bool> = .boolean(default: false)
    static let rel: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let target: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let title: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let url: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedCalloutNode: ParentNodePayload {
  public static let type = "callout"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var kind: CalloutKind?
  public var textFormat: Double?
  public var textStyle: String?
  public var title: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    kind = fields.take("kind", Schema.kind)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    title = fields.take("title", Schema.title)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("kind", kind, Schema.kind)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.put("title", title, Schema.title)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.kind = Schema.kind.resolving(kind)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.title = Schema.title.resolving(title)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let kind: FieldSchema<CalloutKind> = .enumeration(default: CalloutKind.note)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let title: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedCodeHighlightNode: NodePayload {
  public static let type = "code-highlight"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var highlightType: Nullable<String>
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    highlightType = fields.takeNullable("highlightType", Schema.highlightType)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.putNullable("highlightType", highlightType, Schema.highlightType)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.highlightType = Schema.highlightType.resolving(highlightType)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let highlightType: FieldSchema<String?> = .optional(.nullable(.string(default: "")))
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedCollapsibleContainerNode: ParentNodePayload {
  public static let type = "collapsible-container"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var `open`: Bool?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    `open` = fields.take("open", Schema.`open`)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("open", `open`, Schema.`open`)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.`open` = Schema.`open`.resolving(`open`)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let `open`: FieldSchema<Bool> = .boolean(default: false)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedCollapsibleContentNode: ParentNodePayload {
  public static let type = "collapsible-content"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedCollapsibleTitleNode: ParentNodePayload {
  public static let type = "collapsible-title"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedCommentNode: ParentNodePayload {
  public static let type = "comment"
  public static let version = 1
  public var children: [SerializedNode]?
  public var comment: Comment?
  public var direction: Nullable<Never>
  public var format: Double?
  public var indent: Double?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    comment = fields.take("comment", Schema.comment)
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.put("comment", comment, Schema.comment)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.comment = Schema.comment.resolving(comment)
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    return node
  }

  private enum Schema {
    static let comment: FieldSchema<Comment> = .object
    static let direction: FieldSchema<Never?> = .enumeration(default: Never?.none)
    static let format: FieldSchema<Double> = .number(default: 0)
    static let indent: FieldSchema<Double> = .number(default: 0)
  }
}

public struct SerializedEmojiNode: NodePayload {
  public static let type = "emoji"
  public static let version = 1
  public var className: String?
  public var detail: Double?
  public var format: Double?
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    className = fields.take("className", Schema.className)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("className", className, Schema.className)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.className = Schema.className.resolving(className)
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let className: FieldSchema<String> = .string(default: "")
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedFootnoteDefinitionNode: ParentNodePayload {
  public static let type = "footnote-definition"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var label: String?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    label = fields.take("label", Schema.label)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("label", label, Schema.label)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.label = Schema.label.resolving(label)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let label: FieldSchema<String> = .string(default: "")
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedFootnoteReferenceNode: NodePayload {
  public static let type = "footnote-reference"
  public static let version = 1
  public var label: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    label = fields.take("label", Schema.label)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("label", label, Schema.label)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.label = Schema.label.resolving(label)
    return node
  }

  private enum Schema {
    static let label: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedHashtagNode: NodePayload {
  public static let type = "hashtag"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedHeadingNode: ParentNodePayload {
  public static let type = "heading"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var tag: HeadingTag?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    tag = fields.take("tag", Schema.tag)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("tag", tag, Schema.tag)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.tag = Schema.tag.resolving(tag)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let tag: FieldSchema<HeadingTag> = .enumeration(default: HeadingTag.h1)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedHorizontalRuleNode: NodePayload {
  public static let type = "horizontalrule"
  public static let version = 1
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    let fields = try NodeFields(reading: json, as: Self.type)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    let fields = NodeFields(writing: Self.type, over: unknownFields)
    return fields.json
  }

  public func resolved() -> Self {
    self
  }
}

public struct SerializedKeywordNode: NodePayload {
  public static let type = "keyword"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedLayoutContainerNode: ParentNodePayload {
  public static let type = "layout-container"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var figure: Figure?
  public var format: ElementFormat?
  public var indent: Int?
  public var templateColumns: String?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    var state = fields.takeState()
    direction = fields.takeNullable("direction", Schema.direction)
    figure = state.take("figure", Schema.figure)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    templateColumns = fields.take("templateColumns", Schema.templateColumns)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    fields.putState(state)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    var state = fields.takeState()
    fields.putNullable("direction", direction, Schema.direction)
    state.putUnlessDefault("figure", figure, Schema.figure)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("templateColumns", templateColumns, Schema.templateColumns)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.putState(state)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.figure = Schema.figure.omittingDefault(figure)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.templateColumns = Schema.templateColumns.resolving(templateColumns)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let figure: FieldSchema<Figure> = .object
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let templateColumns: FieldSchema<String> = .string(default: "")
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedLayoutItemNode: ParentNodePayload {
  public static let type = "layout-item"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedLineBreakNode: NodePayload {
  public static let type = "linebreak"
  public static let version = 1
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    let fields = try NodeFields(reading: json, as: Self.type)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    let fields = NodeFields(writing: Self.type, over: unknownFields)
    return fields.json
  }

  public func resolved() -> Self {
    self
  }
}

public struct SerializedLinkNode: ParentNodePayload {
  public static let type = "link"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var rel: Nullable<String>
  public var target: Nullable<String>
  public var textFormat: Double?
  public var textStyle: String?
  public var title: Nullable<String>
  public var url: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    rel = fields.takeNullable("rel", Schema.rel)
    target = fields.takeNullable("target", Schema.target)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    title = fields.takeNullable("title", Schema.title)
    url = fields.take("url", Schema.url)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.putNullable("rel", rel, Schema.rel)
    fields.putNullable("target", target, Schema.target)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.putNullable("title", title, Schema.title)
    fields.put("url", url, Schema.url)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.rel = Schema.rel.resolving(rel)
    node.target = Schema.target.resolving(target)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.title = Schema.title.resolving(title)
    node.url = Schema.url.resolving(url)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let rel: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let target: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let title: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let url: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedListNode: ParentNodePayload {
  public static let type = "list"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var listType: ListType?
  public var start: Double?
  public var tag: ListTag?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    listType = fields.take("listType", Schema.listType)
    start = fields.take("start", Schema.start)
    tag = fields.take("tag", Schema.tag)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("listType", listType, Schema.listType)
    fields.put("start", start, Schema.start)
    fields.put("tag", tag, Schema.tag)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.listType = Schema.listType.resolving(listType)
    node.start = Schema.start.resolving(start)
    node.tag = Schema.tag.resolving(tag)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let listType: FieldSchema<ListType> = .aliased(.enumeration(default: ListType.number), ["ol": ListType.number, "ul": ListType.bullet])
    static let start: FieldSchema<Double> = .number(default: 1)
    static let tag: FieldSchema<ListTag> = .enumeration(default: ListTag.ul)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedListItemNode: ParentNodePayload {
  public static let type = "listitem"
  public static let version = 1
  public var children: [SerializedNode]?
  public var checked: Bool?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var value: Double?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    checked = fields.take("checked", Schema.checked)
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    value = fields.take("value", Schema.value)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.put("checked", checked, Schema.checked)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.put("value", value, Schema.value)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.checked = Schema.checked.resolving(checked)
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.value = Schema.value.resolving(value)
    return node
  }

  private enum Schema {
    static let checked: FieldSchema<Bool> = .optional(.boolean(default: false))
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0, max: 128, clamp: true)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let value: FieldSchema<Double> = .number(default: 1)
  }
}

public struct SerializedMarkNode: ParentNodePayload {
  public static let type = "mark"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var ids: [String]?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    ids = fields.take("ids", Schema.ids)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("ids", ids, Schema.ids)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.ids = Schema.ids.resolving(ids)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let ids: FieldSchema<[String]> = .array(.string(default: ""))
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedMentionNode: NodePayload {
  public static let type = "mention"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var mentionName: String?
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mentionName = fields.take("mentionName", Schema.mentionName)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mentionName", mentionName, Schema.mentionName)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mentionName = Schema.mentionName.resolving(mentionName)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mentionName: FieldSchema<String> = .string(default: "")
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedPageBreakNode: NodePayload {
  public static let type = "page-break"
  public static let version = 1
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    let fields = try NodeFields(reading: json, as: Self.type)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    let fields = NodeFields(writing: Self.type, over: unknownFields)
    return fields.json
  }

  public func resolved() -> Self {
    self
  }
}

public struct SerializedParagraphNode: ParentNodePayload {
  public static let type = "paragraph"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .number(default: 0)
    static let textStyle: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedPollNode: NodePayload {
  public static let type = "poll"
  public static let version = 1
  public var options: [PollOption]?
  public var question: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    options = fields.take("options", Schema.options)
    question = fields.take("question", Schema.question)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("options", options, Schema.options)
    fields.put("question", question, Schema.question)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.options = Schema.options.resolving(options)
    node.question = Schema.question.resolving(question)
    return node
  }

  private enum Schema {
    static let options: FieldSchema<[PollOption]> = .array(.object)
    static let question: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedQuoteNode: ParentNodePayload {
  public static let type = "quote"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var shadowRoot: Bool?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    shadowRoot = fields.take("shadowRoot", Schema.shadowRoot)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.putUnlessDefault("shadowRoot", shadowRoot, Schema.shadowRoot)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.shadowRoot = Schema.shadowRoot.omittingDefault(shadowRoot)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let shadowRoot: FieldSchema<Bool> = .boolean(default: false)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedRootNode: ParentNodePayload {
  public static let type = "root"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedStickyNode: NodePayload {
  public static let type = "sticky"
  public static let version = 1
  public var caption: NestedEditor?
  public var color: StickyNoteColor?
  public var xOffset: Double?
  public var yOffset: Double?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    caption = fields.take("caption", Schema.caption)
    color = fields.take("color", Schema.color)
    xOffset = fields.take("xOffset", Schema.xOffset)
    yOffset = fields.take("yOffset", Schema.yOffset)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("caption", caption, Schema.caption)
    fields.put("color", color, Schema.color)
    fields.put("xOffset", xOffset, Schema.xOffset)
    fields.put("yOffset", yOffset, Schema.yOffset)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.caption = Schema.caption.resolving(caption)
    node.color = Schema.color.resolving(color)
    node.xOffset = Schema.xOffset.resolving(xOffset)
    node.yOffset = Schema.yOffset.resolving(yOffset)
    return node
  }

  private enum Schema {
    static let caption: FieldSchema<NestedEditor> = .object
    static let color: FieldSchema<StickyNoteColor> = .enumeration(default: StickyNoteColor.yellow)
    static let xOffset: FieldSchema<Double> = .number(default: 0)
    static let yOffset: FieldSchema<Double> = .number(default: 0)
  }
}

public struct SerializedTabNode: NodePayload {
  public static let type = "tab"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var mode: TabMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .number(default: 2)
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mode: FieldSchema<TabMode> = .enumeration(default: TabMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "\t")
  }
}

public struct SerializedTableNode: ParentNodePayload {
  public static let type = "table"
  public static let version = 1
  public var children: [SerializedNode]?
  public var colWidths: [Double]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var frozenColumnCount: Double?
  public var frozenRowCount: Double?
  public var indent: Int?
  public var rowStriping: Bool?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    colWidths = fields.take("colWidths", Schema.colWidths)
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    frozenColumnCount = fields.take("frozenColumnCount", Schema.frozenColumnCount)
    frozenRowCount = fields.take("frozenRowCount", Schema.frozenRowCount)
    indent = fields.take("indent", Schema.indent)
    rowStriping = fields.take("rowStriping", Schema.rowStriping)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.put("colWidths", colWidths, Schema.colWidths)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("frozenColumnCount", frozenColumnCount, Schema.frozenColumnCount)
    fields.put("frozenRowCount", frozenRowCount, Schema.frozenRowCount)
    fields.put("indent", indent, Schema.indent)
    fields.put("rowStriping", rowStriping, Schema.rowStriping)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.colWidths = Schema.colWidths.resolving(colWidths)
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.frozenColumnCount = Schema.frozenColumnCount.resolving(frozenColumnCount)
    node.frozenRowCount = Schema.frozenRowCount.resolving(frozenRowCount)
    node.indent = Schema.indent.resolving(indent)
    node.rowStriping = Schema.rowStriping.resolving(rowStriping)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let colWidths: FieldSchema<[Double]> = .optional(.array(.number(default: 0)))
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let frozenColumnCount: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let frozenRowCount: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let rowStriping: FieldSchema<Bool> = .optional(.boolean(default: false), omitDefault: true)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedTableCellNode: ParentNodePayload {
  public static let type = "tablecell"
  public static let version = 1
  public var children: [SerializedNode]?
  public var backgroundColor: Nullable<String>
  public var colSpan: Int?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var headerState: Double?
  public var indent: Int?
  public var rowSpan: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var verticalAlign: VerticalAlign?
  public var width: Double?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    backgroundColor = fields.takeNullable("backgroundColor", Schema.backgroundColor)
    colSpan = fields.take("colSpan", Schema.colSpan)
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    headerState = fields.take("headerState", Schema.headerState)
    indent = fields.take("indent", Schema.indent)
    rowSpan = fields.take("rowSpan", Schema.rowSpan)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    verticalAlign = fields.take("verticalAlign", Schema.verticalAlign)
    width = fields.take("width", Schema.width)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("backgroundColor", backgroundColor, Schema.backgroundColor)
    fields.put("colSpan", colSpan, Schema.colSpan)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("headerState", headerState, Schema.headerState)
    fields.put("indent", indent, Schema.indent)
    fields.put("rowSpan", rowSpan, Schema.rowSpan)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    fields.put("verticalAlign", verticalAlign, Schema.verticalAlign)
    fields.put("width", width, Schema.width)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.backgroundColor = Schema.backgroundColor.resolving(backgroundColor)
    node.colSpan = Schema.colSpan.resolving(colSpan)
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.headerState = Schema.headerState.resolving(headerState)
    node.indent = Schema.indent.resolving(indent)
    node.rowSpan = Schema.rowSpan.resolving(rowSpan)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    node.verticalAlign = Schema.verticalAlign.resolving(verticalAlign)
    node.width = Schema.width.resolving(width)
    return node
  }

  private enum Schema {
    static let backgroundColor: FieldSchema<String?> = .nullable(.string(default: ""), defaultAsNull: true)
    static let colSpan: FieldSchema<Int> = .integer(default: 1, min: 1)
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let headerState: FieldSchema<Double> = .number(default: 0)
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let rowSpan: FieldSchema<Int> = .integer(default: 1, min: 1)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
    static let verticalAlign: FieldSchema<VerticalAlign> = .enumeration(default: nil)
    static let width: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
  }
}

public struct SerializedTableRowNode: ParentNodePayload {
  public static let type = "tablerow"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Direction>
  public var format: ElementFormat?
  public var height: Double?
  public var indent: Int?
  public var textFormat: Double?
  public var textStyle: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    height = fields.take("height", Schema.height)
    indent = fields.take("indent", Schema.indent)
    textFormat = fields.take("textFormat", Schema.textFormat)
    textStyle = fields.take("textStyle", Schema.textStyle)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("height", height, Schema.height)
    fields.put("indent", indent, Schema.indent)
    fields.put("textFormat", textFormat, Schema.textFormat)
    fields.put("textStyle", textStyle, Schema.textStyle)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.height = Schema.height.resolving(height)
    node.indent = Schema.indent.resolving(indent)
    node.textFormat = Schema.textFormat.resolving(textFormat)
    node.textStyle = Schema.textStyle.resolving(textStyle)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Direction?> = .enumeration(default: Direction?.none)
    static let format: FieldSchema<ElementFormat> = .enumeration(default: ElementFormat.empty)
    static let height: FieldSchema<Double> = .optional(.number(default: 0))
    static let indent: FieldSchema<Int> = .integer(default: 0, min: 0)
    static let textFormat: FieldSchema<Double> = .optional(.number(default: 0), omitDefault: true)
    static let textStyle: FieldSchema<String> = .optional(.string(default: ""), omitDefault: true)
  }
}

public struct SerializedTextNode: NodePayload {
  public static let type = "text"
  public static let version = 1
  public var detail: Double?
  public var format: Double?
  public var mode: TextMode?
  public var style: String?
  public var text: String?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    detail = fields.take("detail", Schema.detail)
    format = fields.take("format", Schema.format)
    mode = fields.take("mode", Schema.mode)
    style = fields.take("style", Schema.style)
    text = fields.take("text", Schema.text)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.put("detail", detail, Schema.detail)
    fields.put("format", format, Schema.format)
    fields.put("mode", mode, Schema.mode)
    fields.put("style", style, Schema.style)
    fields.put("text", text, Schema.text)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.detail = Schema.detail.resolving(detail)
    node.format = Schema.format.resolving(format)
    node.mode = Schema.mode.resolving(mode)
    node.style = Schema.style.resolving(style)
    node.text = Schema.text.resolving(text)
    return node
  }

  private enum Schema {
    static let detail: FieldSchema<Double> = .aliased(.number(default: 0), ["directionless": 1, "unmergeable": 2])
    static let format: FieldSchema<Double> = .aliased(.number(default: 0), ["bold": 1, "capitalize": 1024, "code": 16, "highlight": 128, "italic": 2, "lowercase": 256, "strikethrough": 4, "subscript": 32, "superscript": 64, "underline": 8, "uppercase": 512])
    static let mode: FieldSchema<TextMode> = .enumeration(default: TextMode.normal)
    static let style: FieldSchema<String> = .string(default: "")
    static let text: FieldSchema<String> = .string(default: "")
  }
}

public struct SerializedThreadNode: ParentNodePayload {
  public static let type = "thread"
  public static let version = 1
  public var children: [SerializedNode]?
  public var direction: Nullable<Never>
  public var format: Double?
  public var indent: Double?
  public var thread: CommentThread?
  public var unknownFields: [String: JSONValue]

  public init(json: JSONValue) throws {
    var fields = try NodeFields(reading: json, as: Self.type)
    children = fields.takeChildren()
    direction = fields.takeNullable("direction", Schema.direction)
    format = fields.take("format", Schema.format)
    indent = fields.take("indent", Schema.indent)
    thread = fields.take("thread", Schema.thread)
    unknownFields = fields.rest
  }

  public var json: JSONValue {
    var fields = NodeFields(writing: Self.type, over: unknownFields)
    fields.putChildren(children)
    fields.putNullable("direction", direction, Schema.direction)
    fields.put("format", format, Schema.format)
    fields.put("indent", indent, Schema.indent)
    fields.put("thread", thread, Schema.thread)
    return fields.json
  }

  public func resolved() -> Self {
    var node = self
    node.direction = Schema.direction.resolving(direction)
    node.format = Schema.format.resolving(format)
    node.indent = Schema.indent.resolving(indent)
    node.thread = Schema.thread.resolving(thread)
    return node
  }

  private enum Schema {
    static let direction: FieldSchema<Never?> = .enumeration(default: Never?.none)
    static let format: FieldSchema<Double> = .number(default: 0)
    static let indent: FieldSchema<Double> = .number(default: 0)
    static let thread: FieldSchema<CommentThread> = .object
  }
}
