// Generated by `bun run codegen` in apps/ios. Don't edit it.

/// A type of file a drawing stores.
public enum DrawingFileType: String, CaseIterable, Sendable {
  case png = "image/png"
  case jpeg = "image/jpeg"
  case svg = "image/svg+xml"
  case webp = "image/webp"
  case avif = "image/avif"
  case gif = "image/gif"
}

/// `MAX_DRAWING_FILE_BYTES`: the largest file a drawing stores, in bytes.
public let maxDrawingFileBytes = 3145728
