// Generated by codegen/font-sizing.ts from the web toolbar.
public enum WebFontSizing {
  public static let defaultSize: Double = 15
  public static func increment(_ current: Double) -> Double {
    if current < 8 { return 8 }
    if current < 12 { return current + 1 }
    if current < 20 { return current + 2 }
    if current < 36 { return current + 4 }
    if current <= 60 { return current + 12 }
    return 72
  }
  public static func decrement(_ current: Double) -> Double {
    if current > 72 { return 72 }
    if current >= 48 { return current - 12 }
    if current >= 24 { return current - 4 }
    if current >= 14 { return current - 2 }
    if current >= 9 { return current - 1 }
    return 8
  }
}
