generate:
  - types
  - client
accessModifier: internal
namingStrategy: idiomatic
filter:
  operations:
    - entities-list
    - entities-search
    - entities-sharedWithMe
    - entities-trash
    - entities-getMetadata
    - entities-getUserTags
    - entities-create
    - entities-update
    - entities-delete
    - entities-restore
    - auth-deletionConfirmation
    - auth-deleteAccount
    - nativeSignIn-exchange
    - tokens-revokeCurrent
    - entities-distillUrl
    - entities-uploadImage
    - documents-replaceMarkdown
