import { type EditorThemeClasses } from "lexical";
import './playground-theme.css';
// import "./theme-default.css"
// import "./theme-dracula.css"

export const theme = {
  code: "rounded-md whitespace-pre block relative font-mono overflow-x-auto my-2 pl-8 py-4 bg-gray-100 dark:bg-gray-800 text-primary-foreground",
  codeHighlight: {
    atrule: "text-indigo-600 dark:text-indigo-400",
    attr: "text-blue-600 dark:text-blue-400",
    boolean: "text-green-600 dark:text-green-400",
    builtin: "text-red-600 dark:text-red-400",
    cdata: "text-gray-600 dark:text-gray-400",
    char: "text-pink-600 dark:text-pink-400",
    class: "text-blue-600 dark:text-blue-400",
    'class-name': "text-green-600 dark:text-green-400",
    comment: "text-gray-400 dark:text-gray-600 italic",
    constant: "text-purple-600 dark:text-purple-400",
    deleted: "text-red-600 dark:text-red-400",
    doctype: "text-gray-600 dark:text-gray-400",
    entity: "text-purple-600 dark:text-purple-400",
    function: "text-blue-600 dark:text-blue-400",
    important: "text-red-600 dark:text-red-400",
    inserted: "text-green-600 dark:text-green-400",
    keyword: "text-purple-600 dark:text-purple-400",
    namespace: "text-purple-600 dark:text-purple-400",
    number: "text-yellow-600 dark:text-yellow-400",
    operator: "text-pink-600 dark:text-pink-400",
    prolog: "text-gray-600 dark:text-gray-400",
    property: "text-teal-600 dark:text-teal-400",
    punctuation: "text-primary-foreground",
    regex: "text-red-600 dark:text-red-400",
    selector: "text-green-600 dark:text-green-400",
    string: "text-teal-600 dark:text-teal-400",
    symbol: "text-orange-600 dark:text-orange-400",
    tag: "text-pink-600 dark:text-pink-400",
    url: "text-blue-600 dark:text-blue-400",
    variable: "text-indigo-600 dark:text-indigo-400"
  },
  table: "PlaygroundEditorTheme__table",
  tableAddColumns: "PlaygroundEditorTheme__tableAddColumns",
  tableAddRows: "PlaygroundEditorTheme__tableAddRows",
  tableCell: "PlaygroundEditorTheme__tableCell",
  tableCellActionButton: "PlaygroundEditorTheme__tableCellActionButton",
  tableCellActionButtonContainer: "PlaygroundEditorTheme__tableCellActionButtonContainer",
  tableCellEditing: "PlaygroundEditorTheme__tableCellEditing",
  tableCellHeader: "PlaygroundEditorTheme__tableCellHeader",
  tableCellPrimarySelected: "PlaygroundEditorTheme__tableCellPrimarySelected",
  tableCellResizer: "PlaygroundEditorTheme__tableCellResizer",
  tableCellSelected: "PlaygroundEditorTheme__tableCellSelected",
  tableCellSortedIndicator: "PlaygroundEditorTheme__tableCellSortedIndicator",
  tableResizeRuler: "PlaygroundEditorTheme__tableCellResizeRuler",
  tableSelected: "PlaygroundEditorTheme__tableSelected",
  heading: {
    h1: 'text-3xl font-semibold mb-2 text-primary-foreground',
    h2: 'text-2xl font-semibold mb-2 text-primary-foreground',
    h3: 'text-xl font-semibold mb-1 text-primary-foreground',
    h4: 'text-lg font-semibold mb-1 text-primary-foreground',
    h5: 'text-md font-semibold mb-0.5 text-primary-foreground',
    h6: 'text-sm font-semibold mb-0.5 text-primary-foreground',
  },
  image: 'editor-image',
  link: 'inline-flex items-center font-medium text-blue-600 dark:text-blue-400 hover:underline',
  list: {
    listitem: 'mx-8 my-2 text-primary-foreground',
    nested: {
      listitem: 'list-none text-primary-foreground',
    },
    ol: 'list-decimal text-primary-foreground',
    ul: 'list-disc text-primary-foreground',
  },
  ltr: 'text-left',
  paragraph: 'm-0 relative text-primary-foreground',
  placeholder: 'text-gray-500 dark:text-gray-400 top-4 left-3 absolute text-sm font-medium pointer-events-none inline-block',
  quote: `m-0 ml-5 border-l-4 border-gray-200 dark:border-gray-700 px-5 py-3 text-primary-foreground`,
  rtl: 'text-right',
  text: {
    bold: 'font-bold text-primary-foreground',
    hashtag: 'editor-text-hashtag text-blue-600 dark:text-blue-400',
    italic: 'italic text-primary-foreground',
    overflowed: 'editor-text-overflowed text-primary-foreground',
    strikethrough: 'line-through text-primary-foreground',
    underline: 'underline text-primary-foreground',
    underlineStrikethrough: 'underline line-through text-primary-foreground',
  },
} satisfies EditorThemeClasses;
