/// <reference types="bun" />
/**
 * Builds the widget into one HTML document and writes it, with the constants
 * the server shares with it, to `dist/index.js`.
 *
 * The document is self-contained on purpose: a host renders an MCP App from the
 * HTML text the `resources/read` answers with, inside a sandbox whose CSP only
 * allows what `_meta.ui.csp` declares, so a second file to fetch would be a
 * second thing that can be refused. Everything but the fonts is inlined.
 */
import { rm, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import * as protocol from "../src/protocol";

const root = join(import.meta.dir, "..");
const dist = join(root, "dist");

const installed = (await Bun.file(
  Bun.resolveSync("@excalidraw/excalidraw/package.json", root),
).json()) as { version: string };
if (installed.version !== protocol.EXCALIDRAW_VERSION) {
  console.error(
    `The editor is ${installed.version} but the widget's fonts are pinned to ${protocol.EXCALIDRAW_VERSION}; update src/protocol.ts.`,
  );
  process.exit(1);
}

await rm(dist, { recursive: true, force: true });

/** Not in a preview; see `src/mermaid-stub.ts`. */
const MERMAID = /^@excalidraw\/mermaid-to-excalidraw(\/.*)?$/;
const mermaidStub = join(root, "src", "mermaid-stub.ts");

const result = await Bun.build({
  entrypoints: [join(root, "src", "widget.tsx")],
  target: "browser",
  format: "esm",
  minify: true,
  // The editor ships a development and a production build; the production one
  // is the smaller of the two and the one the app renders with.
  conditions: ["production"],
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [
    {
      name: "mermaid-stub",
      setup(build) {
        build.onResolve({ filter: MERMAID }, () => ({ path: mermaidStub }));
      },
    },
  ],
});

for (const log of result.logs) console.error(String(log));
if (!result.success) process.exit(1);

const scripts: string[] = [];
const styles: string[] = [];
for (const output of result.outputs) {
  const text = await output.text();
  if (output.path.endsWith(".css")) styles.push(text);
  else if (output.path.endsWith(".js")) scripts.push(text);
  else {
    console.error(
      `Nothing but JS and CSS may come out of this build: ${output.path}`,
    );
    process.exit(1);
  }
}
const [script] = scripts;
if (scripts.length !== 1 || !script) {
  console.error(
    `The document holds one script; the build produced ${scripts.length}.`,
  );
  process.exit(1);
}

/**
 * Excalidraw's stylesheet asks for its own font files next to itself. Inside
 * the sandbox the document has no origin to resolve that against, so the
 * request is pointed at the same pinned CDN the editor loads its other assets
 * from — the one domain `_meta.ui.csp` declares.
 */
const css = styles
  .join("\n")
  .replaceAll(
    /url\((["']?)\.\/fonts\//g,
    `url($1${protocol.EXCALIDRAW_ASSET_BASE}fonts/`,
  );

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lexidraw drawing</title>
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script type="module">${
  // The bundle carries `</script>` inside string literals — the editor writes
  // embed markup — and one of them would otherwise close this tag early.
  script.replaceAll("</script", "<\\/script")
}</script>
</body>
</html>
`;

const generated = "// Generated by scripts/build.ts. Do not edit.\n";
const constants = Object.entries(protocol)
  .map(([name, value]) => `export const ${name} = ${JSON.stringify(value)};`)
  .join("\n");

await mkdir(dist, { recursive: true });
// Two files, because the constants are read on every MCP request and the
// document only when a host asks for the resource.
await writeFile(join(dist, "protocol.js"), `${generated}${constants}\n`);
await writeFile(
  join(dist, "html.js"),
  `${generated}export const DRAWING_PREVIEW_HTML = ${JSON.stringify(html)};\n`,
);

console.log(
  `dist/html.js (${(Buffer.byteLength(html) / 1024 / 1024).toFixed(2)} MB of HTML)`,
);
