/// <reference types="bun" />
/**
 * Builds the widget into one HTML document and writes it, with the constants
 * the server shares with it, to `dist/index.js`.
 *
 * The document is self-contained on purpose: a host renders an MCP App from the
 * HTML text the `resources/read` answers with, inside a sandbox whose CSP only
 * allows what `_meta.ui.csp` declares, so a second file to fetch would be a
 * second thing that can be refused. Everything but the fonts is inlined.
 */
import { rm, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import * as protocol from "../src/protocol";

const root = join(import.meta.dir, "..");
const dist = join(root, "dist");

const installed = (await Bun.file(
  Bun.resolveSync("@excalidraw/excalidraw/package.json", root),
).json()) as { version: string };
if (installed.version !== protocol.EXCALIDRAW_VERSION) {
  console.error(
    `The editor is ${installed.version} but the widget's fonts are pinned to ${protocol.EXCALIDRAW_VERSION}; update src/protocol.ts.`,
  );
  process.exit(1);
}

await rm(dist, { recursive: true, force: true });

/** Not in a preview; see `src/mermaid-stub.ts`. */
const MERMAID = /^@excalidraw\/mermaid-to-excalidraw(\/.*)?$/;
const mermaidStub = join(root, "src", "mermaid-stub.ts");

const result = await Bun.build({
  entrypoints: [join(root, "src", "widget.tsx")],
  target: "browser",
  format: "esm",
  minify: true,
  // The editor ships a development and a production build; the production one
  // is the smaller of the two and the one the app renders with.
  conditions: ["production"],
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [
    {
      name: "mermaid-stub",
      setup(build) {
        build.onResolve({ filter: MERMAID }, () => ({ path: mermaidStub }));
      },
    },
  ],
});

for (const log of result.logs) console.error(String(log));
if (!result.success) process.exit(1);

const scripts: string[] = [];
const styles: string[] = [];
for (const output of result.outputs) {
  const text = await output.text();
  if (output.path.endsWith(".css")) styles.push(text);
  else if (output.path.endsWith(".js")) scripts.push(text);
  else {
    console.error(
      `Nothing but JS and CSS may come out of this build: ${output.path}`,
    );
    process.exit(1);
  }
}
const [script] = scripts;
if (scripts.length !== 1 || !script) {
  console.error(
    `The document holds one script; the build produced ${scripts.length}.`,
  );
  process.exit(1);
}

const css = styles.join("\n");

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lexidraw drawing</title>
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script type="module">${
  // The bundle carries `</script>` inside string literals — the editor writes
  // embed markup — and one of them would otherwise close this tag early.
  script.replaceAll("</script", "<\\/script")
}</script>
</body>
</html>
`;

/**
 * The document the host fetches on every render of the widget, so its size is
 * part of the contract and not an implementation detail. The ceiling sits
 * roughly three quarters of a megabyte above what the editor costs today:
 * enough headroom for a version bump, little enough that pulling a second
 * editor-sized dependency in fails here rather than on a host's connection.
 */
const MAX_DOCUMENT_BYTES = 6_000_000;
const bytes = Buffer.byteLength(html);
if (bytes > MAX_DOCUMENT_BYTES) {
  console.error(
    `The document is ${bytes} bytes, over the ${MAX_DOCUMENT_BYTES} a host is asked to fetch. Drop a dependency or raise the ceiling on purpose.`,
  );
  process.exit(1);
}

const generated = "// Generated by scripts/build.ts. Do not edit.\n";
const constants = Object.entries(protocol)
  .map(([name, value]) => `export const ${name} = ${literal(name, value)};`)
  .join("\n");

/**
 * A constant as the server can read it. Everything in `src/protocol.ts` is
 * data — strings and one object of CSP domains — and this is where that stays
 * true: a function or an undefined export would otherwise be written out as
 * `export const X = undefined;` and read back as a constant that silently is
 * not there.
 */
function literal(name: string, value: unknown): string {
  const json = JSON.stringify(value);
  const data =
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean" ||
    (typeof value === "object" && value !== null);
  if (json === undefined || !data) {
    console.error(
      `src/protocol.ts exports ${name} as a ${value === undefined ? "undefined" : typeof value}; only data can be handed to the server.`,
    );
    process.exit(1);
  }
  return json;
}

await mkdir(dist, { recursive: true });
// Two files, because the constants are read on every MCP request and the
// document only when a host asks for the resource.
await writeFile(join(dist, "protocol.js"), `${generated}${constants}\n`);
await writeFile(
  join(dist, "html.js"),
  `${generated}export const DRAWING_PREVIEW_HTML = ${JSON.stringify(html)};\n`,
);

console.log(
  `dist/html.js (${(bytes / 1024 / 1024).toFixed(2)} MB of HTML, ceiling ${(MAX_DOCUMENT_BYTES / 1024 / 1024).toFixed(2)} MB)`,
);
